import { StudentAnswers } from "./types";

// Eval 1 (bigLetters { name, sound }) - 85% (25 correct: A-Y)
const eval1_85 = { bigLetters: { A: { name: true, sound: true }, B: { name: true, sound: true }, C: { name: true, sound: true }, D: { name: true, sound: true }, E: { name: true, sound: true }, F: { name: true, sound: true }, G: { name: true, sound: true }, H: { name: true, sound: true }, I: { name: true, sound: true }, J: { name: true, sound: true }, K: { name: true, sound: true }, L: { name: true, sound: true }, M: { name: true, sound: true }, N: { name: true, sound: true }, O: { name: true, sound: true }, P: { name: true, sound: true }, Q: { name: true, sound: true }, R: { name: true, sound: true }, S: { name: true, sound: true }, T: { name: true, sound: true }, U: { name: true, sound: true }, V: { name: true, sound: true }, W: { name: true, sound: true }, X: { name: true, sound: true }, Y: { name: true, sound: true }, Z: { name: false, sound: false } } };
const eval1_40 = { bigLetters: { A: { name: true, sound: true }, B: { name: true, sound: true }, C: { name: true, sound: true }, D: { name: true, sound: true }, E: { name: true, sound: true }, F: { name: true, sound: true }, G: { name: true, sound: true }, H: { name: true, sound: true }, I: { name: true, sound: true }, J: { name: true, sound: true }, K: { name: true, sound: true }, L: { name: true, sound: true }, M: { name: true, sound: true }, N: { name: true, sound: true }, O: { name: true, sound: true }, P: { name: true, sound: true }, Q: { name: true, sound: true }, R: { name: true, sound: true }, S: { name: true, sound: true }, T: { name: true, sound: true }, U: { name: false, sound: false }, V: { name: false, sound: false }, W: { name: false, sound: false }, X: { name: false, sound: false }, Y: { name: false, sound: false }, Z: { name: false, sound: false } } };
const eval1_70 = { bigLetters: { A: { name: true, sound: true }, B: { name: true, sound: true }, C: { name: true, sound: true }, D: { name: true, sound: true }, E: { name: true, sound: true }, F: { name: true, sound: true }, G: { name: true, sound: true }, H: { name: true, sound: true }, I: { name: true, sound: true }, J: { name: true, sound: true }, K: { name: true, sound: true }, L: { name: true, sound: true }, M: { name: true, sound: true }, N: { name: true, sound: true }, O: { name: true, sound: true }, P: { name: true, sound: true }, Q: { name: true, sound: true }, R: { name: true, sound: true }, S: { name: true, sound: true }, T: { name: true, sound: true }, U: { name: true, sound: true }, V: { name: true, sound: true }, W: { name: true, sound: true }, X: { name: false, sound: false }, Y: { name: false, sound: false }, Z: { name: false, sound: false } } };
const eval1_76 = { bigLetters: { A: { name: true, sound: true }, B: { name: true, sound: true }, C: { name: true, sound: true }, D: { name: true, sound: true }, E: { name: true, sound: true }, F: { name: true, sound: true }, G: { name: true, sound: true }, H: { name: true, sound: true }, I: { name: true, sound: true }, J: { name: true, sound: true }, K: { name: true, sound: true }, L: { name: true, sound: true }, M: { name: true, sound: true }, N: { name: true, sound: true }, O: { name: true, sound: true }, P: { name: true, sound: true }, Q: { name: true, sound: true }, R: { name: true, sound: true }, S: { name: true, sound: true }, T: { name: true, sound: true }, U: { name: true, sound: true }, V: { name: true, sound: true }, W: { name: true, sound: true }, X: { name: true, sound: true }, Y: { name: false, sound: false }, Z: { name: false, sound: false } } };
const eval1_65 = { bigLetters: { A: { name: true, sound: true }, B: { name: true, sound: true }, C: { name: true, sound: true }, D: { name: true, sound: true }, E: { name: true, sound: true }, F: { name: true, sound: true }, G: { name: true, sound: true }, H: { name: true, sound: true }, I: { name: true, sound: true }, J: { name: true, sound: true }, K: { name: true, sound: true }, L: { name: true, sound: true }, M: { name: true, sound: true }, N: { name: true, sound: true }, O: { name: true, sound: true }, P: { name: true, sound: true }, Q: { name: true, sound: true }, R: { name: true, sound: true }, S: { name: true, sound: true }, T: { name: true, sound: true }, U: { name: true, sound: true }, V: { name: true, sound: true }, W: { name: true, sound: true }, X: { name: false, sound: false }, Y: { name: false, sound: false }, Z: { name: false, sound: false } } };
const eval1_78 = eval1_76;
const eval1_82 = { bigLetters: { A: { name: true, sound: true }, B: { name: true, sound: true }, C: { name: true, sound: true }, D: { name: true, sound: true }, E: { name: true, sound: true }, F: { name: true, sound: true }, G: { name: true, sound: true }, H: { name: true, sound: true }, I: { name: true, sound: true }, J: { name: true, sound: true }, K: { name: true, sound: true }, L: { name: true, sound: true }, M: { name: true, sound: true }, N: { name: true, sound: true }, O: { name: true, sound: true }, P: { name: true, sound: true }, Q: { name: true, sound: true }, R: { name: true, sound: true }, S: { name: true, sound: true }, T: { name: true, sound: true }, U: { name: true, sound: true }, V: { name: true, sound: true }, W: { name: true, sound: true }, X: { name: true, sound: true }, Y: { name: true, sound: true }, Z: { name: false, sound: false } } };
const eval1_58 = { bigLetters: { A: { name: true, sound: true }, B: { name: true, sound: true }, C: { name: true, sound: true }, D: { name: true, sound: true }, E: { name: true, sound: true }, F: { name: true, sound: true }, G: { name: true, sound: true }, H: { name: true, sound: true }, I: { name: true, sound: true }, J: { name: true, sound: true }, K: { name: true, sound: true }, L: { name: true, sound: true }, M: { name: true, sound: true }, N: { name: true, sound: true }, O: { name: true, sound: true }, P: { name: false, sound: false }, Q: { name: false, sound: false }, R: { name: false, sound: false }, S: { name: false, sound: false }, T: { name: false, sound: false }, U: { name: false, sound: false }, V: { name: false, sound: false }, W: { name: false, sound: false }, X: { name: false, sound: false }, Y: { name: false, sound: false }, Z: { name: false, sound: false } } };
const eval1_71 = eval1_70;
const eval1_81 = eval1_82;

// Eval 2 (smallLetters { name, sound }) - 85% (25 correct: a-y)
const eval2_85 = { smallLetters: { a: { name: true, sound: true }, b: { name: true, sound: true }, c: { name: true, sound: true }, d: { name: true, sound: true }, e: { name: true, sound: true }, f: { name: true, sound: true }, g: { name: true, sound: true }, h: { name: true, sound: true }, i: { name: true, sound: true }, j: { name: true, sound: true }, k: { name: true, sound: true }, l: { name: true, sound: true }, m: { name: true, sound: true }, n: { name: true, sound: true }, o: { name: true, sound: true }, p: { name: true, sound: true }, q: { name: true, sound: true }, r: { name: true, sound: true }, s: { name: true, sound: true }, t: { name: true, sound: true }, u: { name: true, sound: true }, v: { name: true, sound: true }, w: { name: true, sound: true }, x: { name: true, sound: true }, y: { name: true, sound: true }, z: { name: false, sound: false } } };
const eval2_40 = { smallLetters: { a: { name: true, sound: true }, b: { name: true, sound: true }, c: { name: true, sound: true }, d: { name: true, sound: true }, e: { name: true, sound: true }, f: { name: true, sound: true }, g: { name: true, sound: true }, h: { name: true, sound: true }, i: { name: true, sound: true }, j: { name: true, sound: true }, k: { name: true, sound: true }, l: { name: true, sound: true }, m: { name: true, sound: true }, n: { name: true, sound: true }, o: { name: true, sound: true }, p: { name: true, sound: true }, q: { name: true, sound: true }, r: { name: true, sound: true }, s: { name: true, sound: true }, t: { name: true, sound: true }, u: { name: false, sound: false }, v: { name: false, sound: false }, w: { name: false, sound: false }, x: { name: false, sound: false }, y: { name: false, sound: false }, z: { name: false, sound: false } } };
const eval2_70 = { smallLetters: { a: { name: true, sound: true }, b: { name: true, sound: true }, c: { name: true, sound: true }, d: { name: true, sound: true }, e: { name: true, sound: true }, f: { name: true, sound: true }, g: { name: true, sound: true }, h: { name: true, sound: true }, i: { name: true, sound: true }, j: { name: true, sound: true }, k: { name: true, sound: true }, l: { name: true, sound: true }, m: { name: true, sound: true }, n: { name: true, sound: true }, o: { name: true, sound: true }, p: { name: true, sound: true }, q: { name: true, sound: true }, r: { name: true, sound: true }, s: { name: true, sound: true }, t: { name: true, sound: true }, u: { name: true, sound: true }, v: { name: true, sound: true }, w: { name: true, sound: true }, x: { name: false, sound: false }, y: { name: false, sound: false }, z: { name: false, sound: false } } };
const eval2_76 = { smallLetters: { a: { name: true, sound: true }, b: { name: true, sound: true }, c: { name: true, sound: true }, d: { name: true, sound: true }, e: { name: true, sound: true }, f: { name: true, sound: true }, g: { name: true, sound: true }, h: { name: true, sound: true }, i: { name: true, sound: true }, j: { name: true, sound: true }, k: { name: true, sound: true }, l: { name: true, sound: true }, m: { name: true, sound: true }, n: { name: true, sound: true }, o: { name: true, sound: true }, p: { name: true, sound: true }, q: { name: true, sound: true }, r: { name: true, sound: true }, s: { name: true, sound: true }, t: { name: true, sound: true }, u: { name: true, sound: true }, v: { name: true, sound: true }, w: { name: true, sound: true }, x: { name: true, sound: true }, y: { name: false, sound: false }, z: { name: false, sound: false } } };
const eval2_65 = { smallLetters: { a: { name: true, sound: true }, b: { name: true, sound: true }, c: { name: true, sound: true }, d: { name: true, sound: true }, e: { name: true, sound: true }, f: { name: true, sound: true }, g: { name: true, sound: true }, h: { name: true, sound: true }, i: { name: true, sound: true }, j: { name: true, sound: true }, k: { name: true, sound: true }, l: { name: true, sound: true }, m: { name: true, sound: true }, n: { name: true, sound: true }, o: { name: true, sound: true }, p: { name: true, sound: true }, q: { name: true, sound: true }, r: { name: true, sound: true }, s: { name: true, sound: true }, t: { name: true, sound: true }, u: { name: true, sound: true }, v: { name: true, sound: true }, w: { name: true, sound: true }, x: { name: false, sound: false }, y: { name: false, sound: false }, z: { name: false, sound: false } } };
const eval2_78 = eval2_76;
const eval2_82 = { smallLetters: { a: { name: true, sound: true }, b: { name: true, sound: true }, c: { name: true, sound: true }, d: { name: true, sound: true }, e: { name: true, sound: true }, f: { name: true, sound: true }, g: { name: true, sound: true }, h: { name: true, sound: true }, i: { name: true, sound: true }, j: { name: true, sound: true }, k: { name: true, sound: true }, l: { name: true, sound: true }, m: { name: true, sound: true }, n: { name: true, sound: true }, o: { name: true, sound: true }, p: { name: true, sound: true }, q: { name: true, sound: true }, r: { name: true, sound: true }, s: { name: true, sound: true }, t: { name: true, sound: true }, u: { name: true, sound: true }, v: { name: true, sound: true }, w: { name: true, sound: true }, x: { name: true, sound: true }, y: { name: true, sound: true }, z: { name: false, sound: false } } };
const eval2_58 = { smallLetters: { a: { name: true, sound: true }, b: { name: true, sound: true }, c: { name: true, sound: true }, d: { name: true, sound: true }, e: { name: true, sound: true }, f: { name: true, sound: true }, g: { name: true, sound: true }, h: { name: true, sound: true }, i: { name: true, sound: true }, j: { name: true, sound: true }, k: { name: true, sound: true }, l: { name: true, sound: true }, m: { name: true, sound: true }, n: { name: true, sound: true }, o: { name: true, sound: true }, p: { name: false, sound: false }, q: { name: false, sound: false }, r: { name: false, sound: false }, s: { name: false, sound: false }, t: { name: false, sound: false }, u: { name: false, sound: false }, v: { name: false, sound: false }, w: { name: false, sound: false }, x: { name: false, sound: false }, y: { name: false, sound: false }, z: { name: false, sound: false } } };
const eval2_71 = eval2_70;
const eval2_81 = eval2_82;

// Eval 3 (bigLetters { correct }) - 85% (22 correct: A-V)
const eval3_85 = { bigLetters: { A: { correct: true }, B: { correct: true }, C: { correct: true }, D: { correct: true }, E: { correct: true }, F: { correct: true }, G: { correct: true }, H: { correct: true }, I: { correct: true }, J: { correct: true }, K: { correct: true }, L: { correct: true }, M: { correct: true }, N: { correct: true }, O: { correct: true }, P: { correct: true }, Q: { correct: true }, R: { correct: true }, S: { correct: true }, T: { correct: true }, U: { correct: true }, V: { correct: true }, W: { correct: false }, X: { correct: false }, Y: { correct: false }, Z: { correct: false } } };
const eval3_40 = { bigLetters: { A: { correct: true }, B: { correct: true }, C: { correct: true }, D: { correct: true }, E: { correct: true }, F: { correct: true }, G: { correct: true }, H: { correct: true }, I: { correct: true }, J: { correct: true }, K: { correct: false }, L: { correct: false }, M: { correct: false }, N: { correct: false }, O: { correct: false }, P: { correct: false }, Q: { correct: false }, R: { correct: false }, S: { correct: false }, T: { correct: false }, U: { correct: false }, V: { correct: false }, W: { correct: false }, X: { correct: false }, Y: { correct: false }, Z: { correct: false } } };
const eval3_70 = { bigLetters: { A: { correct: true }, B: { correct: true }, C: { correct: true }, D: { correct: true }, E: { correct: true }, F: { correct: true }, G: { correct: true }, H: { correct: true }, I: { correct: true }, J: { correct: true }, K: { correct: true }, L: { correct: true }, M: { correct: true }, N: { correct: true }, O: { correct: true }, P: { correct: true }, Q: { correct: true }, R: { correct: true }, S: { correct: true }, T: { correct: false }, U: { correct: false }, V: { correct: false }, W: { correct: false }, X: { correct: false }, Y: { correct: false }, Z: { correct: false } } };
const eval3_76 = { bigLetters: { A: { correct: true }, B: { correct: true }, C: { correct: true }, D: { correct: true }, E: { correct: true }, F: { correct: true }, G: { correct: true }, H: { correct: true }, I: { correct: true }, J: { correct: true }, K: { correct: true }, L: { correct: true }, M: { correct: true }, N: { correct: true }, O: { correct: true }, P: { correct: true }, Q: { correct: true }, R: { correct: true }, S: { correct: true }, T: { correct: true }, U: { correct: true }, V: { correct: false }, W: { correct: false }, X: { correct: false }, Y: { correct: false }, Z: { correct: false } } };
const eval3_65 = { bigLetters: { A: { correct: true }, B: { correct: true }, C: { correct: true }, D: { correct: true }, E: { correct: true }, F: { correct: true }, G: { correct: true }, H: { correct: true }, I: { correct: true }, J: { correct: true }, K: { correct: true }, L: { correct: true }, M: { correct: true }, N: { correct: true }, O: { correct: true }, P: { correct: true }, Q: { correct: true }, R: { correct: true }, S: { correct: false }, T: { correct: false }, U: { correct: false }, V: { correct: false }, W: { correct: false }, X: { correct: false }, Y: { correct: false }, Z: { correct: false } } };
const eval3_78 = eval3_76;
const eval3_82 = { bigLetters: { A: { correct: true }, B: { correct: true }, C: { correct: true }, D: { correct: true }, E: { correct: true }, F: { correct: true }, G: { correct: true }, H: { correct: true }, I: { correct: true }, J: { correct: true }, K: { correct: true }, L: { correct: true }, M: { correct: true }, N: { correct: true }, O: { correct: true }, P: { correct: true }, Q: { correct: true }, R: { correct: true }, S: { correct: true }, T: { correct: true }, U: { correct: true }, V: { correct: true }, W: { correct: true }, X: { correct: false }, Y: { correct: false }, Z: { correct: false } } };
const eval3_58 = { bigLetters: { A: { correct: true }, B: { correct: true }, C: { correct: true }, D: { correct: true }, E: { correct: true }, F: { correct: true }, G: { correct: true }, H: { correct: true }, I: { correct: true }, J: { correct: true }, K: { correct: true }, L: { correct: true }, M: { correct: true }, N: { correct: true }, O: { correct: false }, P: { correct: false }, Q: { correct: false }, R: { correct: false }, S: { correct: false }, T: { correct: false }, U: { correct: false }, V: { correct: false }, W: { correct: false }, X: { correct: false }, Y: { correct: false }, Z: { correct: false } } };
const eval3_71 = eval3_70;
const eval3_81 = eval3_82;

// Eval 4 (smallLetters { correct }) - same pattern as eval3 but with lowercase
const eval4_85 = { smallLetters: { a: { correct: true }, b: { correct: true }, c: { correct: true }, d: { correct: true }, e: { correct: true }, f: { correct: true }, g: { correct: true }, h: { correct: true }, i: { correct: true }, j: { correct: true }, k: { correct: true }, l: { correct: true }, m: { correct: true }, n: { correct: true }, o: { correct: true }, p: { correct: true }, q: { correct: true }, r: { correct: true }, s: { correct: true }, t: { correct: true }, u: { correct: true }, v: { correct: true }, w: { correct: false }, x: { correct: false }, y: { correct: false }, z: { correct: false } } };
const eval4_40 = { smallLetters: { a: { correct: true }, b: { correct: true }, c: { correct: true }, d: { correct: true }, e: { correct: true }, f: { correct: true }, g: { correct: true }, h: { correct: true }, i: { correct: true }, j: { correct: true }, k: { correct: false }, l: { correct: false }, m: { correct: false }, n: { correct: false }, o: { correct: false }, p: { correct: false }, q: { correct: false }, r: { correct: false }, s: { correct: false }, t: { correct: false }, u: { correct: false }, v: { correct: false }, w: { correct: false }, x: { correct: false }, y: { correct: false }, z: { correct: false } } };
const eval4_70 = { smallLetters: { a: { correct: true }, b: { correct: true }, c: { correct: true }, d: { correct: true }, e: { correct: true }, f: { correct: true }, g: { correct: true }, h: { correct: true }, i: { correct: true }, j: { correct: true }, k: { correct: true }, l: { correct: true }, m: { correct: true }, n: { correct: true }, o: { correct: true }, p: { correct: true }, q: { correct: true }, r: { correct: true }, s: { correct: true }, t: { correct: false }, u: { correct: false }, v: { correct: false }, w: { correct: false }, x: { correct: false }, y: { correct: false }, z: { correct: false } } };
const eval4_76 = { smallLetters: { a: { correct: true }, b: { correct: true }, c: { correct: true }, d: { correct: true }, e: { correct: true }, f: { correct: true }, g: { correct: true }, h: { correct: true }, i: { correct: true }, j: { correct: true }, k: { correct: true }, l: { correct: true }, m: { correct: true }, n: { correct: true }, o: { correct: true }, p: { correct: true }, q: { correct: true }, r: { correct: true }, s: { correct: true }, t: { correct: true }, u: { correct: true }, v: { correct: false }, w: { correct: false }, x: { correct: false }, y: { correct: false }, z: { correct: false } } };
const eval4_65 = { smallLetters: { a: { correct: true }, b: { correct: true }, c: { correct: true }, d: { correct: true }, e: { correct: true }, f: { correct: true }, g: { correct: true }, h: { correct: true }, i: { correct: true }, j: { correct: true }, k: { correct: true }, l: { correct: true }, m: { correct: true }, n: { correct: true }, o: { correct: true }, p: { correct: true }, q: { correct: true }, r: { correct: true }, s: { correct: false }, t: { correct: false }, u: { correct: false }, v: { correct: false }, w: { correct: false }, x: { correct: false }, y: { correct: false }, z: { correct: false } } };
const eval4_78 = eval4_76;
const eval4_82 = { smallLetters: { a: { correct: true }, b: { correct: true }, c: { correct: true }, d: { correct: true }, e: { correct: true }, f: { correct: true }, g: { correct: true }, h: { correct: true }, i: { correct: true }, j: { correct: true }, k: { correct: true }, l: { correct: true }, m: { correct: true }, n: { correct: true }, o: { correct: true }, p: { correct: true }, q: { correct: true }, r: { correct: true }, s: { correct: true }, t: { correct: true }, u: { correct: true }, v: { correct: true }, w: { correct: true }, x: { correct: false }, y: { correct: false }, z: { correct: false } } };
const eval4_58 = { smallLetters: { a: { correct: true }, b: { correct: true }, c: { correct: true }, d: { correct: true }, e: { correct: true }, f: { correct: true }, g: { correct: true }, h: { correct: true }, i: { correct: true }, j: { correct: true }, k: { correct: true }, l: { correct: true }, m: { correct: true }, n: { correct: true }, o: { correct: false }, p: { correct: false }, q: { correct: false }, r: { correct: false }, s: { correct: false }, t: { correct: false }, u: { correct: false }, v: { correct: false }, w: { correct: false }, x: { correct: false }, y: { correct: false }, z: { correct: false } } };
const eval4_71 = eval4_70;
const eval4_81 = eval4_82;

// Eval 5 (wordPairs, syllables, numOfSyllables all { correct })
const eval5_85 = { wordPairs: { "chat/rat": { correct: true }, "fleur/table": { correct: true }, "bateau/chapeau": { correct: true }, "pain/main": { correct: true }, "lune/porte": { correct: false } }, syllables: { "ma-man": { correct: true }, "ta-ble": { correct: true }, "cha-peau": { correct: true }, "voi-ture": { correct: true }, "ba-na-ne": { correct: false } }, numOfSyllables: { "chat": { correct: true }, "livre": { correct: true }, "éléphant": { correct: true }, "chocolat": { correct: true }, "papillon": { correct: false } } };
const eval5_40 = { wordPairs: { "chat/rat": { correct: true }, "fleur/table": { correct: true }, "bateau/chapeau": { correct: false }, "pain/main": { correct: false }, "lune/porte": { correct: false } }, syllables: { "ma-man": { correct: true }, "ta-ble": { correct: true }, "cha-peau": { correct: false }, "voi-ture": { correct: false }, "ba-na-ne": { correct: false } }, numOfSyllables: { "chat": { correct: true }, "livre": { correct: true }, "éléphant": { correct: false }, "chocolat": { correct: false }, "papillon": { correct: false } } };
const eval5_70 = { wordPairs: { "chat/rat": { correct: true }, "fleur/table": { correct: true }, "bateau/chapeau": { correct: true }, "pain/main": { correct: true }, "lune/porte": { correct: true } }, syllables: { "ma-man": { correct: true }, "ta-ble": { correct: true }, "cha-peau": { correct: true }, "voi-ture": { correct: true }, "ba-na-ne": { correct: false } }, numOfSyllables: { "chat": { correct: true }, "livre": { correct: true }, "éléphant": { correct: true }, "chocolat": { correct: true }, "papillon": { correct: false } } };
const eval5_76 = { wordPairs: { "chat/rat": { correct: true }, "fleur/table": { correct: true }, "bateau/chapeau": { correct: true }, "pain/main": { correct: true }, "lune/porte": { correct: true } }, syllables: { "ma-man": { correct: true }, "ta-ble": { correct: true }, "cha-peau": { correct: true }, "voi-ture": { correct: true }, "ba-na-ne": { correct: true } }, numOfSyllables: { "chat": { correct: true }, "livre": { correct: true }, "éléphant": { correct: true }, "chocolat": { correct: true }, "papillon": { correct: false } } };
const eval5_65 = { wordPairs: { "chat/rat": { correct: true }, "fleur/table": { correct: true }, "bateau/chapeau": { correct: true }, "pain/main": { correct: true }, "lune/porte": { correct: true } }, syllables: { "ma-man": { correct: true }, "ta-ble": { correct: true }, "cha-peau": { correct: true }, "voi-ture": { correct: true }, "ba-na-ne": { correct: true } }, numOfSyllables: { "chat": { correct: true }, "livre": { correct: true }, "éléphant": { correct: true }, "chocolat": { correct: false }, "papillon": { correct: false } } };
const eval5_78 = eval5_76;
const eval5_82 = { wordPairs: { "chat/rat": { correct: true }, "fleur/table": { correct: true }, "bateau/chapeau": { correct: true }, "pain/main": { correct: true }, "lune/porte": { correct: true } }, syllables: { "ma-man": { correct: true }, "ta-ble": { correct: true }, "cha-peau": { correct: true }, "voi-ture": { correct: true }, "ba-na-ne": { correct: true } }, numOfSyllables: { "chat": { correct: true }, "livre": { correct: true }, "éléphant": { correct: true }, "chocolat": { correct: true }, "papillon": { correct: true } } };
const eval5_58 = { wordPairs: { "chat/rat": { correct: true }, "fleur/table": { correct: true }, "bateau/chapeau": { correct: true }, "pain/main": { correct: false }, "lune/porte": { correct: false } }, syllables: { "ma-man": { correct: true }, "ta-ble": { correct: true }, "cha-peau": { correct: true }, "voi-ture": { correct: false }, "ba-na-ne": { correct: false } }, numOfSyllables: { "chat": { correct: true }, "livre": { correct: true }, "éléphant": { correct: true }, "chocolat": { correct: false }, "papillon": { correct: false } } };
const eval5_71 = eval5_70;
const eval5_81 = eval5_82;

// Eval 6 (startOfWord + endOfWord, both { sound, correct })
const eval6_85 = { startOfWord: { "maison": { sound: "/m/", correct: true }, "ballon": { sound: "/b/", correct: true }, "soleil": { sound: "/s/", correct: true }, "fenêtre": { sound: "/f/", correct: true }, "chat": { sound: "/ʃ/", correct: true } }, endOfWord: { "chat": { sound: "/a/", correct: true }, "pomme": { sound: "/m/", correct: true }, "souris": { sound: "/i/", correct: true }, "sac": { sound: "/k/", correct: true }, "fil": { sound: "/l/", correct: false } } };
const eval6_40 = { startOfWord: { "maison": { sound: "/m/", correct: true }, "ballon": { sound: "/b/", correct: true }, "soleil": { sound: "/s/", correct: false }, "fenêtre": { sound: "/f/", correct: false }, "chat": { sound: "/ʃ/", correct: false } }, endOfWord: { "chat": { sound: "/a/", correct: true }, "pomme": { sound: "/m/", correct: true }, "souris": { sound: "/i/", correct: false }, "sac": { sound: "/k/", correct: false }, "fil": { sound: "/l/", correct: false } } };
const eval6_70 = { startOfWord: { "maison": { sound: "/m/", correct: true }, "ballon": { sound: "/b/", correct: true }, "soleil": { sound: "/s/", correct: true }, "fenêtre": { sound: "/f/", correct: true }, "chat": { sound: "/ʃ/", correct: true } }, endOfWord: { "chat": { sound: "/a/", correct: true }, "pomme": { sound: "/m/", correct: true }, "souris": { sound: "/i/", correct: true }, "sac": { sound: "/k/", correct: true }, "fil": { sound: "/l/", correct: false } } };
const eval6_76 = { startOfWord: { "maison": { sound: "/m/", correct: true }, "ballon": { sound: "/b/", correct: true }, "soleil": { sound: "/s/", correct: true }, "fenêtre": { sound: "/f/", correct: true }, "chat": { sound: "/ʃ/", correct: true } }, endOfWord: { "chat": { sound: "/a/", correct: true }, "pomme": { sound: "/m/", correct: true }, "souris": { sound: "/i/", correct: true }, "sac": { sound: "/k/", correct: true }, "fil": { sound: "/l/", correct: true } } };
const eval6_65 = { startOfWord: { "maison": { sound: "/m/", correct: true }, "ballon": { sound: "/b/", correct: true }, "soleil": { sound: "/s/", correct: true }, "fenêtre": { sound: "/f/", correct: true }, "chat": { sound: "/ʃ/", correct: false } }, endOfWord: { "chat": { sound: "/a/", correct: true }, "pomme": { sound: "/m/", correct: true }, "souris": { sound: "/i/", correct: true }, "sac": { sound: "/k/", correct: true }, "fil": { sound: "/l/", correct: true } } };
const eval6_78 = eval6_76;
const eval6_82 = eval6_76;
const eval6_58 = { startOfWord: { "maison": { sound: "/m/", correct: true }, "ballon": { sound: "/b/", correct: true }, "soleil": { sound: "/s/", correct: true }, "fenêtre": { sound: "/f/", correct: false }, "chat": { sound: "/ʃ/", correct: false } }, endOfWord: { "chat": { sound: "/a/", correct: true }, "pomme": { sound: "/m/", correct: true }, "souris": { sound: "/i/", correct: false }, "sac": { sound: "/k/", correct: false }, "fil": { sound: "/l/", correct: false } } };
const eval6_71 = eval6_70;
const eval6_81 = eval6_82;

// Eval 7 (syllables + soundRows, both { correct })
const eval7_85 = { syllables: { "ma": { correct: true }, "li": { correct: true }, "po": { correct: true }, "ru": { correct: true }, "sa": { correct: true }, "il": { correct: true }, "or": { correct: true }, "pa": { correct: true }, "mi": { correct: true }, "bol": { correct: false } }, soundRows: { 0: { word: "a – e – t", sound: "/a/", correct: "a" }, 1: { word: "e – s – n", sound: "/e/", correct: "e" }, 2: { word: "t – a – s", sound: "/t/", correct: "t" }, 3: { word: "n – e – s", sound: "/s/", correct: "s" }, 4: { word: "a – t – n", sound: "/n/", correct: "n" } } };
const eval7_40 = { syllables: { "ma": { correct: true }, "li": { correct: true }, "po": { correct: false }, "ru": { correct: false }, "sa": { correct: false }, "il": { correct: false }, "or": { correct: false }, "pa": { correct: false }, "mi": { correct: false }, "bol": { correct: false } }, soundRows: { 0: { word: "a – e – t", sound: "/a/", correct: "a" }, 1: { word: "e – s – n", sound: "/e/", correct: "e" }, 2: { word: "t – a – s", sound: "/t/", correct: false }, 3: { word: "n – e – s", sound: "/s/", correct: false }, 4: { word: "a – t – n", sound: "/n/", correct: false } } };
const eval7_70 = { syllables: { "ma": { correct: true }, "li": { correct: true }, "po": { correct: true }, "ru": { correct: true }, "sa": { correct: true }, "il": { correct: true }, "or": { correct: true }, "pa": { correct: true }, "mi": { correct: true }, "bol": { correct: false } }, soundRows: { 0: { word: "a – e – t", sound: "/a/", correct: "a" }, 1: { word: "e – s – n", sound: "/e/", correct: "e" }, 2: { word: "t – a – s", sound: "/t/", correct: "t" }, 3: { word: "n – e – s", sound: "/s/", correct: "s" }, 4: { word: "a – t – n", sound: "/n/", correct: false } } };
const eval7_76 = { syllables: { "ma": { correct: true }, "li": { correct: true }, "po": { correct: true }, "ru": { correct: true }, "sa": { correct: true }, "il": { correct: true }, "or": { correct: true }, "pa": { correct: true }, "mi": { correct: true }, "bol": { correct: true } }, soundRows: { 0: { word: "a – e – t", sound: "/a/", correct: "a" }, 1: { word: "e – s – n", sound: "/e/", correct: "e" }, 2: { word: "t – a – s", sound: "/t/", correct: "t" }, 3: { word: "n – e – s", sound: "/s/", correct: "s" }, 4: { word: "a – t – n", sound: "/n/", correct: false } } };
const eval7_65 = { syllables: { "ma": { correct: true }, "li": { correct: true }, "po": { correct: true }, "ru": { correct: true }, "sa": { correct: true }, "il": { correct: true }, "or": { correct: true }, "pa": { correct: true }, "mi": { correct: true }, "bol": { correct: true } }, soundRows: { 0: { word: "a – e – t", sound: "/a/", correct: "a" }, 1: { word: "e – s – n", sound: "/e/", correct: "e" }, 2: { word: "t – a – s", sound: "/t/", correct: "t" }, 3: { word: "n – e – s", sound: "/s/", correct: false }, 4: { word: "a – t – n", sound: "/n/", correct: false } } };
const eval7_78 = eval7_76;
const eval7_82 = eval7_76;
const eval7_58 = { syllables: { "ma": { correct: true }, "li": { correct: true }, "po": { correct: true }, "ru": { correct: true }, "sa": { correct: false }, "il": { correct: false }, "or": { correct: false }, "pa": { correct: false }, "mi": { correct: false }, "bol": { correct: false } }, soundRows: { 0: { word: "a – e – t", sound: "/a/", correct: "a" }, 1: { word: "e – s – n", sound: "/e/", correct: "e" }, 2: { word: "t – a – s", sound: "/t/", correct: false }, 3: { word: "n – e – s", sound: "/s/", correct: false }, 4: { word: "a – t – n", sound: "/n/", correct: false } } };
const eval7_71 = eval7_70;
const eval7_81 = eval7_82;

// Eval 8 (frequentWords + openClosedList + complexList, all { correct })
const eval8_85 = { frequentWords: { "le": { correct: true }, "de": { correct: true }, "un": { correct: true }, "petit": { correct: true }, "papa": { correct: true }, "maman": { correct: true }, "c'est": { correct: true }, "voici": { correct: true }, "dit": { correct: true }, "ami": { correct: true }, "avec": { correct: true }, "grand": { correct: true }, "a": { correct: true }, "regarde": { correct: true }, "pour": { correct: true }, "une": { correct: true }, "elle": { correct: true }, "est": { correct: true }, "il y a": { correct: true }, "ici": { correct: true }, "dans": { correct: true }, "mon": { correct: true }, "aller": { correct: true }, "cherche": { correct: false }, "j'aime": { correct: true } }, openClosedList: { "ba": { correct: true }, "li": { correct: true }, "por": { correct: true }, "val": { correct: true }, "tur": { correct: false } }, complexList: { "pla": { correct: true }, "bri": { correct: true }, "tro": { correct: true }, "flan": { correct: true }, "gros": { correct: false } } };
const eval8_40 = { frequentWords: { "le": { correct: true }, "de": { correct: true }, "un": { correct: true }, "petit": { correct: false }, "papa": { correct: false }, "maman": { correct: false }, "c'est": { correct: false }, "voici": { correct: false }, "dit": { correct: false }, "ami": { correct: true }, "avec": { correct: false }, "grand": { correct: false }, "a": { correct: false }, "regarde": { correct: false }, "pour": { correct: false }, "une": { correct: true }, "elle": { correct: false }, "est": { correct: false }, "il y a": { correct: false }, "ici": { correct: false }, "dans": { correct: false }, "mon": { correct: false }, "aller": { correct: false }, "cherche": { correct: false }, "j'aime": { correct: false } }, openClosedList: { "ba": { correct: true }, "li": { correct: true }, "por": { correct: false }, "val": { correct: false }, "tur": { correct: false } }, complexList: { "pla": { correct: true }, "bri": { correct: true }, "tro": { correct: false }, "flan": { correct: false }, "gros": { correct: false } } };
const eval8_70 = { frequentWords: { "le": { correct: true }, "de": { correct: true }, "un": { correct: true }, "petit": { correct: true }, "papa": { correct: true }, "maman": { correct: true }, "c'est": { correct: true }, "voici": { correct: true }, "dit": { correct: true }, "ami": { correct: true }, "avec": { correct: true }, "grand": { correct: true }, "a": { correct: true }, "regarde": { correct: true }, "pour": { correct: true }, "une": { correct: true }, "elle": { correct: true }, "est": { correct: true }, "il y a": { correct: true }, "ici": { correct: true }, "dans": { correct: false }, "mon": { correct: false }, "aller": { correct: false }, "cherche": { correct: false }, "j'aime": { correct: true } }, openClosedList: { "ba": { correct: true }, "li": { correct: true }, "por": { correct: true }, "val": { correct: true }, "tur": { correct: false } }, complexList: { "pla": { correct: true }, "bri": { correct: true }, "tro": { correct: true }, "flan": { correct: true }, "gros": { correct: false } } };
const eval8_76 = { frequentWords: { "le": { correct: true }, "de": { correct: true }, "un": { correct: true }, "petit": { correct: true }, "papa": { correct: true }, "maman": { correct: true }, "c'est": { correct: true }, "voici": { correct: true }, "dit": { correct: true }, "ami": { correct: true }, "avec": { correct: true }, "grand": { correct: true }, "a": { correct: true }, "regarde": { correct: true }, "pour": { correct: true }, "une": { correct: true }, "elle": { correct: true }, "est": { correct: true }, "il y a": { correct: true }, "ici": { correct: true }, "dans": { correct: true }, "mon": { correct: true }, "aller": { correct: true }, "cherche": { correct: false }, "j'aime": { correct: true } }, openClosedList: { "ba": { correct: true }, "li": { correct: true }, "por": { correct: true }, "val": { correct: true }, "tur": { correct: true } }, complexList: { "pla": { correct: true }, "bri": { correct: true }, "tro": { correct: true }, "flan": { correct: true }, "gros": { correct: false } } };
const eval8_65 = { frequentWords: { "le": { correct: true }, "de": { correct: true }, "un": { correct: true }, "petit": { correct: true }, "papa": { correct: true }, "maman": { correct: true }, "c'est": { correct: true }, "voici": { correct: true }, "dit": { correct: true }, "ami": { correct: true }, "avec": { correct: true }, "grand": { correct: true }, "a": { correct: true }, "regarde": { correct: true }, "pour": { correct: true }, "une": { correct: true }, "elle": { correct: true }, "est": { correct: true }, "il y a": { correct: true }, "ici": { correct: true }, "dans": { correct: true }, "mon": { correct: true }, "aller": { correct: true }, "cherche": { correct: true }, "j'aime": { correct: true } }, openClosedList: { "ba": { correct: true }, "li": { correct: true }, "por": { correct: true }, "val": { correct: true }, "tur": { correct: true } }, complexList: { "pla": { correct: true }, "bri": { correct: true }, "tro": { correct: true }, "flan": { correct: false }, "gros": { correct: false } } };
const eval8_78 = eval8_76;
const eval8_82 = eval8_76;
const eval8_58 = { frequentWords: { "le": { correct: true }, "de": { correct: true }, "un": { correct: true }, "petit": { correct: true }, "papa": { correct: true }, "maman": { correct: true }, "c'est": { correct: true }, "voici": { correct: true }, "dit": { correct: false }, "ami": { correct: false }, "avec": { correct: false }, "grand": { correct: false }, "a": { correct: false }, "regarde": { correct: false }, "pour": { correct: false }, "une": { correct: true }, "elle": { correct: false }, "est": { correct: false }, "il y a": { correct: false }, "ici": { correct: false }, "dans": { correct: false }, "mon": { correct: false }, "aller": { correct: false }, "cherche": { correct: false }, "j'aime": { correct: false } }, openClosedList: { "ba": { correct: true }, "li": { correct: true }, "por": { correct: true }, "val": { correct: false }, "tur": { correct: false } }, complexList: { "pla": { correct: true }, "bri": { correct: true }, "tro": { correct: false }, "flan": { correct: false }, "gros": { correct: false } } };
const eval8_71 = eval8_70;
const eval8_81 = eval8_82;

// Eval 9 (frequentWordsSlice { correct })
const eval9_85 = { frequentWordsSlice: { "maman": { correct: true }, "c'est": { correct: true }, "voici": { correct: true }, "dit": { correct: true }, "ami": { correct: true }, "avec": { correct: true }, "grand": { correct: true }, "a": { correct: true }, "regarde": { correct: true }, "pour": { correct: true }, "une": { correct: true }, "elle": { correct: true }, "est": { correct: true }, "il y a": { correct: true }, "ici": { correct: false } } };
const eval9_40 = { frequentWordsSlice: { "maman": { correct: true }, "c'est": { correct: true }, "voici": { correct: false }, "dit": { correct: false }, "ami": { correct: false }, "avec": { correct: false }, "grand": { correct: false }, "a": { correct: false }, "regarde": { correct: false }, "pour": { correct: false }, "une": { correct: false }, "elle": { correct: false }, "est": { correct: false }, "il y a": { correct: false }, "ici": { correct: false } } };
const eval9_70 = { frequentWordsSlice: { "maman": { correct: true }, "c'est": { correct: true }, "voici": { correct: true }, "dit": { correct: true }, "ami": { correct: true }, "avec": { correct: true }, "grand": { correct: true }, "a": { correct: true }, "regarde": { correct: true }, "pour": { correct: true }, "une": { correct: true }, "elle": { correct: true }, "est": { correct: true }, "il y a": { correct: true }, "ici": { correct: false } } };
const eval9_76 = { frequentWordsSlice: { "maman": { correct: true }, "c'est": { correct: true }, "voici": { correct: true }, "dit": { correct: true }, "ami": { correct: true }, "avec": { correct: true }, "grand": { correct: true }, "a": { correct: true }, "regarde": { correct: true }, "pour": { correct: true }, "une": { correct: true }, "elle": { correct: true }, "est": { correct: true }, "il y a": { correct: true }, "ici": { correct: true } } };
const eval9_65 = { frequentWordsSlice: { "maman": { correct: true }, "c'est": { correct: true }, "voici": { correct: true }, "dit": { correct: true }, "ami": { correct: true }, "avec": { correct: true }, "grand": { correct: true }, "a": { correct: true }, "regarde": { correct: true }, "pour": { correct: true }, "une": { correct: true }, "elle": { correct: true }, "est": { correct: true }, "il y a": { correct: false }, "ici": { correct: false } } };
const eval9_78 = eval9_76;
const eval9_82 = eval9_76;
const eval9_58 = { frequentWordsSlice: { "maman": { correct: true }, "c'est": { correct: true }, "voici": { correct: true }, "dit": { correct: true }, "ami": { correct: true }, "avec": { correct: true }, "grand": { correct: false }, "a": { correct: false }, "regarde": { correct: false }, "pour": { correct: false }, "une": { correct: true }, "elle": { correct: false }, "est": { correct: false }, "il y a": { correct: false }, "ici": { correct: false } } };
const eval9_71 = eval9_70;
const eval9_81 = eval9_82;

// Eval 10 (data { correct }) - 10 words only
const eval10_85 = { data: { "chat": { correct: true }, "agneau": { correct: true }, "montagne": { correct: true }, "oiseau": { correct: true }, "maison": { correct: true }, "bateau": { correct: true }, "soupe": { correct: true }, "lait": { correct: true }, "auto": { correct: true }, "poire": { correct: false } } };
const eval10_40 = { data: { "chat": { correct: true }, "agneau": { correct: true }, "montagne": { correct: false }, "oiseau": { correct: false }, "maison": { correct: false }, "bateau": { correct: false }, "soupe": { correct: false }, "lait": { correct: false }, "auto": { correct: false }, "poire": { correct: false } } };
const eval10_70 = { data: { "chat": { correct: true }, "agneau": { correct: true }, "montagne": { correct: true }, "oiseau": { correct: true }, "maison": { correct: true }, "bateau": { correct: true }, "soupe": { correct: true }, "lait": { correct: false }, "auto": { correct: false }, "poire": { correct: false } } };
const eval10_76 = { data: { "chat": { correct: true }, "agneau": { correct: true }, "montagne": { correct: true }, "oiseau": { correct: true }, "maison": { correct: true }, "bateau": { correct: true }, "soupe": { correct: true }, "lait": { correct: true }, "auto": { correct: false }, "poire": { correct: false } } };
const eval10_65 = { data: { "chat": { correct: true }, "agneau": { correct: true }, "montagne": { correct: true }, "oiseau": { correct: true }, "maison": { correct: true }, "bateau": { correct: true }, "soupe": { correct: true }, "lait": { correct: true }, "auto": { correct: true }, "poire": { correct: false } } };
const eval10_78 = eval10_76;
const eval10_82 = eval10_76;
const eval10_58 = { data: { "chat": { correct: true }, "agneau": { correct: true }, "montagne": { correct: true }, "oiseau": { correct: true }, "maison": { correct: false }, "bateau": { correct: false }, "soupe": { correct: false }, "lait": { correct: false }, "auto": { correct: false }, "poire": { correct: false } } };
const eval10_71 = eval10_70;
const eval10_81 = eval10_82;

// Eval 11 (data { forms, correct })
const eval11_85 = { data: { "grand": { forms: ["grand", "grande", "grands", "grandes"], correct: true }, "petit": { forms: ["petit", "petite", "petits", "petites"], correct: true }, "beau": { forms: ["beau", "belle", "beaux", "belles"], correct: true }, "chaud": { forms: ["chaud", "chaude", "chauds", "chaudes"], correct: true }, "blanc": { forms: ["blanc", "blanche", "blancs", "blanches"], correct: false } } };
const eval11_40 = { data: { "grand": { forms: ["grand", "grande", "grands", "grandes"], correct: true }, "petit": { forms: ["petit", "petite", "petits", "petites"], correct: false }, "beau": { forms: ["beau", "belle", "beaux", "belles"], correct: false }, "chaud": { forms: ["chaud", "chaude", "chauds", "chaudes"], correct: false }, "blanc": { forms: ["blanc", "blanche", "blancs", "blanches"], correct: false } } };
const eval11_70 = { data: { "grand": { forms: ["grand", "grande", "grands", "grandes"], correct: true }, "petit": { forms: ["petit", "petite", "petits", "petites"], correct: true }, "beau": { forms: ["beau", "belle", "beaux", "belles"], correct: true }, "chaud": { forms: ["chaud", "chaude", "chauds", "chaudes"], correct: true }, "blanc": { forms: ["blanc", "blanche", "blancs", "blanches"], correct: false } } };
const eval11_76 = { data: { "grand": { forms: ["grand", "grande", "grands", "grandes"], correct: true }, "petit": { forms: ["petit", "petite", "petits", "petites"], correct: true }, "beau": { forms: ["beau", "belle", "beaux", "belles"], correct: true }, "chaud": { forms: ["chaud", "chaude", "chauds", "chaudes"], correct: true }, "blanc": { forms: ["blanc", "blanche", "blancs", "blanches"], correct: true } } };
const eval11_65 = { data: { "grand": { forms: ["grand", "grande", "grands", "grandes"], correct: true }, "petit": { forms: ["petit", "petite", "petits", "petites"], correct: true }, "beau": { forms: ["beau", "belle", "beaux", "belles"], correct: true }, "chaud": { forms: ["chaud", "chaude", "chauds", "chaudes"], correct: false }, "blanc": { forms: ["blanc", "blanche", "blancs", "blanches"], correct: false } } };
const eval11_78 = eval11_76;
const eval11_82 = eval11_76;
const eval11_58 = { data: { "grand": { forms: ["grand", "grande", "grands", "grandes"], correct: true }, "petit": { forms: ["petit", "petite", "petits", "petites"], correct: true }, "beau": { forms: ["beau", "belle", "beaux", "belles"], correct: true }, "chaud": { forms: ["chaud", "chaude", "chauds", "chaudes"], correct: false }, "blanc": { forms: ["blanc", "blanche", "blancs", "blanches"], correct: false } } };
const eval11_71 = eval11_70;
const eval11_81 = eval11_82;

// Eval 12 (data { correct }) - 3 sentences
const eval12_85 = { data: { "Le chat dort sur le canapé.": { correct: true }, "Ma maman dort sur le canapé.": { correct: true }, "L'enfant dort sur le canapé.": { correct: false } } };
const eval12_40 = { data: { "Le chat dort sur le canapé.": { correct: true }, "Ma maman dort sur le canapé.": { correct: false }, "L'enfant dort sur le canapé.": { correct: false } } };
const eval12_70 = { data: { "Le chat dort sur le canapé.": { correct: true }, "Ma maman dort sur le canapé.": { correct: true }, "L'enfant dort sur le canapé.": { correct: true } } };
const eval12_76 = eval12_70;
const eval12_65 = { data: { "Le chat dort sur le canapé.": { correct: true }, "Ma maman dort sur le canapé.": { correct: true }, "L'enfant dort sur le canapé.": { correct: false } } };
const eval12_78 = eval12_76;
const eval12_82 = eval12_76;
const eval12_58 = { data: { "Le chat dort sur le canapé.": { correct: true }, "Ma maman dort sur le canapé.": { correct: false }, "L'enfant dort sur le canapé.": { correct: false } } };
const eval12_71 = eval12_70;
const eval12_81 = eval12_82;

// Eval 13 (data { correct }) - 10 words
const eval13_85 = { data: { "travail": { correct: true }, "soleil": { correct: true }, "réveil": { correct: true }, "fauteuil": { correct: true }, "écureuil": { correct: true }, "grenouille": { correct: true }, "chandail": { correct: true }, "appareil": { correct: true }, "seuil": { correct: true }, "citrouille": { correct: false } } };
const eval13_40 = { data: { "travail": { correct: true }, "soleil": { correct: true }, "réveil": { correct: false }, "fauteuil": { correct: false }, "écureuil": { correct: false }, "grenouille": { correct: false }, "chandail": { correct: false }, "appareil": { correct: false }, "seuil": { correct: false }, "citrouille": { correct: false } } };
const eval13_70 = { data: { "travail": { correct: true }, "soleil": { correct: true }, "réveil": { correct: true }, "fauteuil": { correct: true }, "écureuil": { correct: true }, "grenouille": { correct: true }, "chandail": { correct: true }, "appareil": { correct: false }, "seuil": { correct: false }, "citrouille": { correct: false } } };
const eval13_76 = { data: { "travail": { correct: true }, "soleil": { correct: true }, "réveil": { correct: true }, "fauteuil": { correct: true }, "écureuil": { correct: true }, "grenouille": { correct: true }, "chandail": { correct: true }, "appareil": { correct: true }, "seuil": { correct: false }, "citrouille": { correct: false } } };
const eval13_65 = { data: { "travail": { correct: true }, "soleil": { correct: true }, "réveil": { correct: true }, "fauteuil": { correct: true }, "écureuil": { correct: true }, "grenouille": { correct: true }, "chandail": { correct: true }, "appareil": { correct: true }, "seuil": { correct: true }, "citrouille": { correct: false } } };
const eval13_78 = eval13_76;
const eval13_82 = eval13_76;
const eval13_58 = { data: { "travail": { correct: true }, "soleil": { correct: true }, "réveil": { correct: true }, "fauteuil": { correct: true }, "écureuil": { correct: false }, "grenouille": { correct: false }, "chandail": { correct: false }, "appareil": { correct: false }, "seuil": { correct: false }, "citrouille": { correct: false } } };
const eval13_71 = eval13_70;
const eval13_81 = eval13_82;

// Eval 14 (data { answer, correct }) - 5 comprehension questions
const eval14_85 = { data: { "Où vont Sophie et Marc?": { answer: "Au parc", correct: true }, "Qui va au parc avec eux?": { answer: "Leur chien Félix / Félix", correct: true }, "De quelle couleur est le ballon?": { answer: "Rouge", correct: true }, "Que font-ils après le jeu?": { answer: "Ils mangent des sandwichs et boivent du jus", correct: true }, "Comment se sentent-ils à la fin?": { answer: "Fatigués mais heureux", correct: false } } };
const eval14_40 = { data: { "Où vont Sophie et Marc?": { answer: "Au parc", correct: true }, "Qui va au parc avec eux?": { answer: "Leur chien Félix / Félix", correct: false }, "De quelle couleur est le ballon?": { answer: "Rouge", correct: false }, "Que font-ils après le jeu?": { answer: "Ils mangent des sandwichs et boivent du jus", correct: false }, "Comment se sentent-ils à la fin?": { answer: "Fatigués mais heureux", correct: false } } };
const eval14_70 = { data: { "Où vont Sophie et Marc?": { answer: "Au parc", correct: true }, "Qui va au parc avec eux?": { answer: "Leur chien Félix / Félix", correct: true }, "De quelle couleur est le ballon?": { answer: "Rouge", correct: true }, "Que font-ils après le jeu?": { answer: "Ils mangent des sandwichs et boivent du jus", correct: true }, "Comment se sentent-ils à la fin?": { answer: "Fatigués mais heureux", correct: false } } };
const eval14_76 = { data: { "Où vont Sophie et Marc?": { answer: "Au parc", correct: true }, "Qui va au parc avec eux?": { answer: "Leur chien Félix / Félix", correct: true }, "De quelle couleur est le ballon?": { answer: "Rouge", correct: true }, "Que font-ils après le jeu?": { answer: "Ils mangent des sandwichs et boivent du jus", correct: true }, "Comment se sentent-ils à la fin?": { answer: "Fatigués mais heureux", correct: true } } };
const eval14_65 = { data: { "Où vont Sophie et Marc?": { answer: "Au parc", correct: true }, "Qui va au parc avec eux?": { answer: "Leur chien Félix / Félix", correct: true }, "De quelle couleur est le ballon?": { answer: "Rouge", correct: true }, "Que font-ils après le jeu?": { answer: "Ils mangent des sandwichs et boivent du jus", correct: true }, "Comment se sentent-ils à la fin?": { answer: "Fatigués mais heureux", correct: false } } };
const eval14_78 = eval14_76;
const eval14_82 = eval14_76;
const eval14_58 = { data: { "Où vont Sophie et Marc?": { answer: "Au parc", correct: true }, "Qui va au parc avec eux?": { answer: "Leur chien Félix / Félix", correct: true }, "De quelle couleur est le ballon?": { answer: "Rouge", correct: false }, "Que font-ils après le jeu?": { answer: "Ils mangent des sandwichs et boivent du jus", correct: false }, "Comment se sentent-ils à la fin?": { answer: "Fatigués mais heureux", correct: false } } };
const eval14_71 = eval14_70;
const eval14_81 = eval14_82;

// Eval 15 (data { answer, correct }) - 5 comprehension questions
const eval15_85 = { data: { "Comment s'appelle le chat?": { answer: "Minou", correct: true }, "De quelle couleur est le chat?": { answer: "Noir et blanc", correct: true }, "Qu'est-ce que Minou aime faire?": { answer: "Dormir sur le lit et jouer avec une balle rouge", correct: true }, "De quelle couleur est son bol?": { answer: "Bleu", correct: true }, "Quand est-ce que Minou boit du lait?": { answer: "Tous les matins", correct: false } } };
const eval15_40 = { data: { "Comment s'appelle le chat?": { answer: "Minou", correct: true }, "De quelle couleur est le chat?": { answer: "Noir et blanc", correct: false }, "Qu'est-ce que Minou aime faire?": { answer: "Dormir sur le lit et jouer avec une balle rouge", correct: false }, "De quelle couleur est son bol?": { answer: "Bleu", correct: false }, "Quand est-ce que Minou boit du lait?": { answer: "Tous les matins", correct: false } } };
const eval15_70 = { data: { "Comment s'appelle le chat?": { answer: "Minou", correct: true }, "De quelle couleur est le chat?": { answer: "Noir et blanc", correct: true }, "Qu'est-ce que Minou aime faire?": { answer: "Dormir sur le lit et jouer avec une balle rouge", correct: true }, "De quelle couleur est son bol?": { answer: "Bleu", correct: true }, "Quand est-ce que Minou boit du lait?": { answer: "Tous les matins", correct: false } } };
const eval15_76 = { data: { "Comment s'appelle le chat?": { answer: "Minou", correct: true }, "De quelle couleur est le chat?": { answer: "Noir et blanc", correct: true }, "Qu'est-ce que Minou aime faire?": { answer: "Dormir sur le lit et jouer avec une balle rouge", correct: true }, "De quelle couleur est son bol?": { answer: "Bleu", correct: true }, "Quand est-ce que Minou boit du lait?": { answer: "Tous les matins", correct: true } } };
const eval15_65 = { data: { "Comment s'appelle le chat?": { answer: "Minou", correct: true }, "De quelle couleur est le chat?": { answer: "Noir et blanc", correct: true }, "Qu'est-ce que Minou aime faire?": { answer: "Dormir sur le lit et jouer avec une balle rouge", correct: true }, "De quelle couleur est son bol?": { answer: "Bleu", correct: true }, "Quand est-ce que Minou boit du lait?": { answer: "Tous les matins", correct: false } } };
const eval15_78 = eval15_76;
const eval15_82 = eval15_76;
const eval15_58 = { data: { "Comment s'appelle le chat?": { answer: "Minou", correct: true }, "De quelle couleur est le chat?": { answer: "Noir et blanc", correct: true }, "Qu'est-ce que Minou aime faire?": { answer: "Dormir sur le lit et jouer avec une balle rouge", correct: false }, "De quelle couleur est son bol?": { answer: "Bleu", correct: false }, "Quand est-ce que Minou boit du lait?": { answer: "Tous les matins", correct: false } } };
const eval15_71 = eval15_70;
const eval15_81 = eval15_82;

// Fallback aliases for old generic names (deprecated)
const answers85 = eval3_85;
const answers40 = eval3_40;
const answers70 = eval3_70;
const answers76 = eval3_76;
const answers65 = eval3_65;
const answers78 = eval3_78;
const answers82 = eval3_82;
const answers58 = eval3_58;
const answers71 = eval3_71;
const answers81 = eval3_81;

export const answers: StudentAnswers[] = [
  // Student 1 (Amélie Dubois) - Good performer (85%)
  { id: 1, lastModified: "2024-05-01T10:00:00Z", studentId: 1, classId: 1, unitDataId: 1, required: true, answers: eval1_85, comment: "Great work!" },
  { id: 2, lastModified: "2024-05-02T10:00:00Z", studentId: 1, classId: 1, unitDataId: 2, required: true, answers: eval2_85, comment: "Excellent progress!" },
  { id: 3, lastModified: "2024-05-03T10:00:00Z", studentId: 1, classId: 1, unitDataId: 3, required: true, answers: answers85, comment: "Good understanding" },
  { id: 4, lastModified: "2024-05-04T10:00:00Z", studentId: 1, classId: 1, unitDataId: 4, required: true, answers: eval4_85, comment: "Keep it up!" },
  { id: 5, lastModified: "2024-05-05T10:00:00Z", studentId: 1, classId: 1, unitDataId: 5, required: true, answers: eval5_85, comment: "Strong work" },
  { id: 6, lastModified: "2024-05-06T10:00:00Z", studentId: 1, classId: 1, unitDataId: 6, required: true, answers: eval6_85, comment: "Excellent!" },
  { id: 7, lastModified: "2024-05-07T10:00:00Z", studentId: 1, classId: 1, unitDataId: 7, required: true, answers: eval7_85, comment: "Great effort" },
  { id: 8, lastModified: "2024-05-08T10:00:00Z", studentId: 1, classId: 1, unitDataId: 8, required: true, answers: eval8_85, comment: "Good job" },
  { id: 9, lastModified: "2024-05-09T10:00:00Z", studentId: 1, classId: 1, unitDataId: 9, required: true, answers: eval9_85, comment: "Wonderful!" },
  { id: 10, lastModified: "2024-05-10T10:00:00Z", studentId: 1, classId: 1, unitDataId: 10, required: true, answers: eval10_85, comment: "Keep going!" },
  { id: 11, lastModified: "2024-05-11T10:00:00Z", studentId: 1, classId: 1, unitDataId: 11, required: true, answers: eval11_85, comment: "Good work" },
  { id: 12, lastModified: "2024-05-12T10:00:00Z", studentId: 1, classId: 1, unitDataId: 12, required: true, answers: eval12_85, comment: "Excellent effort!" },
  { id: 13, lastModified: "2024-05-13T10:00:00Z", studentId: 1, classId: 1, unitDataId: 13, required: true, answers: eval13_85, comment: "Outstanding!" },
  { id: 131, lastModified: "2024-05-14T10:00:00Z", studentId: 1, classId: 1, unitDataId: 14, required: true, answers: eval14_85, comment: "Outstanding comprehension!" },
  { id: 132, lastModified: "2024-05-15T10:00:00Z", studentId: 1, classId: 1, unitDataId: 15, required: true, answers: eval15_85, comment: "Excellent understanding!" },
  
  // Student 2 (Benjamin Tremblay) - Struggling (40%)
  { id: 14, lastModified: "2024-05-01T10:00:00Z", studentId: 2, classId: 1, unitDataId: 1, required: true, answers: eval1_40, comment: "Needs more practice" },
  { id: 15, lastModified: "2024-05-02T10:00:00Z", studentId: 2, classId: 1, unitDataId: 2, required: true, answers: eval2_40, comment: "Let's work on this together" },
  { id: 16, lastModified: "2024-05-03T10:00:00Z", studentId: 2, classId: 1, unitDataId: 3, required: true, answers: answers40, comment: "Keep practicing" },
  { id: 17, lastModified: "2024-05-04T10:00:00Z", studentId: 2, classId: 1, unitDataId: 4, required: true, answers: eval4_40, comment: "Getting better!" },
  { id: 18, lastModified: "2024-05-05T10:00:00Z", studentId: 2, classId: 1, unitDataId: 5, required: true, answers: eval5_40, comment: "Review needed" },
  { id: 19, lastModified: "2024-05-06T10:00:00Z", studentId: 2, classId: 1, unitDataId: 6, required: true, answers: eval6_40, comment: "Some improvement" },
  { id: 20, lastModified: "2024-05-07T10:00:00Z", studentId: 2, classId: 1, unitDataId: 7, required: true, answers: eval7_40, comment: "More effort needed" },
  { id: 21, lastModified: "2024-05-08T10:00:00Z", studentId: 2, classId: 1, unitDataId: 8, required: true, answers: eval8_40, comment: "Continue practicing" },
  { id: 22, lastModified: "2024-05-09T10:00:00Z", studentId: 2, classId: 1, unitDataId: 9, required: true, answers: eval9_40, comment: "Good effort!" },
  { id: 23, lastModified: "2024-05-10T10:00:00Z", studentId: 2, classId: 1, unitDataId: 10, required: true, answers: eval10_40, comment: "Keep trying" },
  { id: 24, lastModified: "2024-05-11T10:00:00Z", studentId: 2, classId: 1, unitDataId: 11, required: true, answers: eval11_40, comment: "Work in progress" },
  { id: 25, lastModified: "2024-05-12T10:00:00Z", studentId: 2, classId: 1, unitDataId: 12, required: true, answers: eval12_40, comment: "Let's practice more" },
  { id: 26, lastModified: "2024-05-13T10:00:00Z", studentId: 2, classId: 1, unitDataId: 13, required: true, answers: eval13_40, comment: "Steady progress" },
  { id: 133, lastModified: "2024-05-14T10:00:00Z", studentId: 2, classId: 1, unitDataId: 14, required: true, answers: eval14_40, comment: "Review needed" },
  { id: 134, lastModified: "2024-05-15T10:00:00Z", studentId: 2, classId: 1, unitDataId: 15, required: true, answers: eval15_40, comment: "More practice required" },

  // Student 3 (Charlotte Gagnon) - Average (70%)
  { id: 27, lastModified: "2024-05-01T10:00:00Z", studentId: 3, classId: 1, unitDataId: 1, required: true, answers: eval1_70, comment: "Good effort" },
  { id: 28, lastModified: "2024-05-02T10:00:00Z", studentId: 3, classId: 1, unitDataId: 2, required: true, answers: eval2_70, comment: "Nice work" },
  { id: 29, lastModified: "2024-05-03T10:00:00Z", studentId: 3, classId: 1, unitDataId: 3, required: true, answers: answers70, comment: "Decent progress" },
  { id: 30, lastModified: "2024-05-04T10:00:00Z", studentId: 3, classId: 1, unitDataId: 4, required: true, answers: eval4_70, comment: "Solid work" },
  { id: 31, lastModified: "2024-05-05T10:00:00Z", studentId: 3, classId: 1, unitDataId: 5, required: true, answers: eval5_70, comment: "Keep it up" },
  { id: 32, lastModified: "2024-05-06T10:00:00Z", studentId: 3, classId: 1, unitDataId: 6, required: true, answers: eval6_70, comment: "Great!" },
  { id: 33, lastModified: "2024-05-07T10:00:00Z", studentId: 3, classId: 1, unitDataId: 7, required: true, answers: eval7_70, comment: "Good progress" },
  { id: 34, lastModified: "2024-05-08T10:00:00Z", studentId: 3, classId: 1, unitDataId: 8, required: true, answers: eval8_70, comment: "Nice effort" },
  { id: 35, lastModified: "2024-05-09T10:00:00Z", studentId: 3, classId: 1, unitDataId: 9, required: true, answers: eval9_70, comment: "Improving!" },
  { id: 36, lastModified: "2024-05-10T10:00:00Z", studentId: 3, classId: 1, unitDataId: 10, required: true, answers: eval10_70, comment: "Solid effort" },
  { id: 37, lastModified: "2024-05-11T10:00:00Z", studentId: 3, classId: 1, unitDataId: 11, required: true, answers: eval11_70, comment: "Good work" },
  { id: 38, lastModified: "2024-05-12T10:00:00Z", studentId: 3, classId: 1, unitDataId: 12, required: true, answers: eval12_70, comment: "Well done!" },
  { id: 39, lastModified: "2024-05-13T10:00:00Z", studentId: 3, classId: 1, unitDataId: 13, required: true, answers: eval13_70, comment: "Good effort" },
  { id: 135, lastModified: "2024-05-14T10:00:00Z", studentId: 3, classId: 1, unitDataId: 14, required: true, answers: eval14_70, comment: "Good understanding" },
  { id: 136, lastModified: "2024-05-15T10:00:00Z", studentId: 3, classId: 1, unitDataId: 15, required: true, answers: eval15_70, comment: "Solid comprehension" },

  // Student 4 (David Roy) - Good (76%)
  { id: 40, lastModified: "2024-05-01T10:00:00Z", studentId: 4, classId: 1, unitDataId: 1, required: true, answers: eval1_76, comment: "Solid work" },
  { id: 41, lastModified: "2024-05-02T10:00:00Z", studentId: 4, classId: 1, unitDataId: 2, required: true, answers: eval2_76, comment: "Great!" },
  { id: 42, lastModified: "2024-05-03T10:00:00Z", studentId: 4, classId: 1, unitDataId: 3, required: true, answers: answers76, comment: "Nice work" },
  { id: 43, lastModified: "2024-05-04T10:00:00Z", studentId: 4, classId: 1, unitDataId: 4, required: true, answers: eval4_76, comment: "Good effort" },
  { id: 44, lastModified: "2024-05-05T10:00:00Z", studentId: 4, classId: 1, unitDataId: 5, required: true, answers: eval5_76, comment: "Well done" },
  { id: 45, lastModified: "2024-05-06T10:00:00Z", studentId: 4, classId: 1, unitDataId: 6, required: true, answers: eval6_76, comment: "Excellent" },
  { id: 46, lastModified: "2024-05-07T10:00:00Z", studentId: 4, classId: 1, unitDataId: 7, required: true, answers: eval7_76, comment: "Great progress" },
  { id: 47, lastModified: "2024-05-08T10:00:00Z", studentId: 4, classId: 1, unitDataId: 8, required: true, answers: eval8_76, comment: "Strong work" },
  { id: 48, lastModified: "2024-05-09T10:00:00Z", studentId: 4, classId: 1, unitDataId: 9, required: true, answers: eval9_76, comment: "Very good" },
  { id: 49, lastModified: "2024-05-10T10:00:00Z", studentId: 4, classId: 1, unitDataId: 10, required: true, answers: eval10_76, comment: "Nice effort" },
  { id: 50, lastModified: "2024-05-11T10:00:00Z", studentId: 4, classId: 1, unitDataId: 11, required: true, answers: eval11_76, comment: "Keep it up" },
  { id: 51, lastModified: "2024-05-12T10:00:00Z", studentId: 4, classId: 1, unitDataId: 12, required: true, answers: eval12_76, comment: "Wonderful" },
  { id: 52, lastModified: "2024-05-13T10:00:00Z", studentId: 4, classId: 1, unitDataId: 13, required: true, answers: eval13_76, comment: "Excellent work" },
  { id: 137, lastModified: "2024-05-14T10:00:00Z", studentId: 4, classId: 1, unitDataId: 14, required: true, answers: eval14_76, comment: "Very good" },
  { id: 138, lastModified: "2024-05-15T10:00:00Z", studentId: 4, classId: 1, unitDataId: 15, required: true, answers: eval15_76, comment: "Well done" },

  // Student 5 (Émilie Côté) - Adequate (65%)
  { id: 53, lastModified: "2024-05-01T10:00:00Z", studentId: 5, classId: 1, unitDataId: 1, required: true, answers: eval1_65, comment: "Good progress" },
  { id: 54, lastModified: "2024-05-02T10:00:00Z", studentId: 5, classId: 1, unitDataId: 2, required: true, answers: eval2_65, comment: "Nice work" },
  { id: 55, lastModified: "2024-05-03T10:00:00Z", studentId: 5, classId: 1, unitDataId: 3, required: true, answers: answers65, comment: "Solid effort" },
  { id: 56, lastModified: "2024-05-04T10:00:00Z", studentId: 5, classId: 1, unitDataId: 4, required: true, answers: eval4_65, comment: "Keep going" },
  { id: 57, lastModified: "2024-05-05T10:00:00Z", studentId: 5, classId: 1, unitDataId: 5, required: true, answers: eval5_65, comment: "Good work" },
  { id: 58, lastModified: "2024-05-06T10:00:00Z", studentId: 5, classId: 1, unitDataId: 6, required: true, answers: eval6_65, comment: "Well done" },
  { id: 59, lastModified: "2024-05-07T10:00:00Z", studentId: 5, classId: 1, unitDataId: 7, required: true, answers: eval7_65, comment: "Nice effort" },
  { id: 60, lastModified: "2024-05-08T10:00:00Z", studentId: 5, classId: 1, unitDataId: 8, required: true, answers: eval8_65, comment: "Getting better" },
  { id: 61, lastModified: "2024-05-09T10:00:00Z", studentId: 5, classId: 1, unitDataId: 9, required: true, answers: eval9_65, comment: "Good job" },
  { id: 62, lastModified: "2024-05-10T10:00:00Z", studentId: 5, classId: 1, unitDataId: 10, required: true, answers: eval10_65, comment: "Improving" },
  { id: 63, lastModified: "2024-05-11T10:00:00Z", studentId: 5, classId: 1, unitDataId: 11, required: true, answers: eval11_65, comment: "Fine work" },
  { id: 64, lastModified: "2024-05-12T10:00:00Z", studentId: 5, classId: 1, unitDataId: 12, required: true, answers: eval12_65, comment: "Good effort" },
  { id: 65, lastModified: "2024-05-13T10:00:00Z", studentId: 5, classId: 1, unitDataId: 13, required: true, answers: eval13_65, comment: "Decent work" },
  { id: 139, lastModified: "2024-05-14T10:00:00Z", studentId: 5, classId: 1, unitDataId: 14, required: true, answers: eval14_65, comment: "Decent work" },
  { id: 140, lastModified: "2024-05-15T10:00:00Z", studentId: 5, classId: 1, unitDataId: 15, required: true, answers: eval15_65, comment: "Fair progress" },

  // Student 6 (François Bouchard) - Good (78%)
  { id: 66, lastModified: "2024-05-01T10:00:00Z", studentId: 6, classId: 1, unitDataId: 1, required: true, answers: eval1_78, comment: "Great work" },
  { id: 67, lastModified: "2024-05-02T10:00:00Z", studentId: 6, classId: 1, unitDataId: 2, required: true, answers: eval2_78, comment: "Excellent" },
  { id: 68, lastModified: "2024-05-03T10:00:00Z", studentId: 6, classId: 1, unitDataId: 3, required: true, answers: answers78, comment: "Very good" },
  { id: 69, lastModified: "2024-05-04T10:00:00Z", studentId: 6, classId: 1, unitDataId: 4, required: true, answers: eval4_78, comment: "Strong work" },
  { id: 70, lastModified: "2024-05-05T10:00:00Z", studentId: 6, classId: 1, unitDataId: 5, required: true, answers: eval5_78, comment: "Nice effort" },
  { id: 71, lastModified: "2024-05-06T10:00:00Z", studentId: 6, classId: 1, unitDataId: 6, required: true, answers: eval6_78, comment: "Wonderful" },
  { id: 72, lastModified: "2024-05-07T10:00:00Z", studentId: 6, classId: 1, unitDataId: 7, required: true, answers: eval7_78, comment: "Excellent work" },
  { id: 73, lastModified: "2024-05-08T10:00:00Z", studentId: 6, classId: 1, unitDataId: 8, required: true, answers: eval8_78, comment: "Great progress" },
  { id: 74, lastModified: "2024-05-09T10:00:00Z", studentId: 6, classId: 1, unitDataId: 9, required: true, answers: eval9_78, comment: "Well done" },
  { id: 75, lastModified: "2024-05-10T10:00:00Z", studentId: 6, classId: 1, unitDataId: 10, required: true, answers: eval10_78, comment: "Keep it up" },
  { id: 76, lastModified: "2024-05-11T10:00:00Z", studentId: 6, classId: 1, unitDataId: 11, required: true, answers: eval11_78, comment: "Good job" },
  { id: 77, lastModified: "2024-05-12T10:00:00Z", studentId: 6, classId: 1, unitDataId: 12, required: true, answers: eval12_78, comment: "Outstanding" },
  { id: 78, lastModified: "2024-05-13T10:00:00Z", studentId: 6, classId: 1, unitDataId: 13, required: true, answers: eval13_78, comment: "Excellent effort" },
  { id: 141, lastModified: "2024-05-14T10:00:00Z", studentId: 6, classId: 1, unitDataId: 14, required: true, answers: eval14_78, comment: "Excellent work" },
  { id: 142, lastModified: "2024-05-15T10:00:00Z", studentId: 6, classId: 1, unitDataId: 15, required: true, answers: eval15_78, comment: "Outstanding work" },

  // Student 7 (Gabrielle Gauthier) - Excellent (82%)
  { id: 79, lastModified: "2024-05-01T10:00:00Z", studentId: 7, classId: 1, unitDataId: 1, required: true, answers: eval1_82, comment: "Excellent!" },
  { id: 80, lastModified: "2024-05-02T10:00:00Z", studentId: 7, classId: 1, unitDataId: 2, required: true, answers: eval2_82, comment: "Outstanding!" },
  { id: 81, lastModified: "2024-05-03T10:00:00Z", studentId: 7, classId: 1, unitDataId: 3, required: true, answers: answers82, comment: "Wonderful!" },
  { id: 82, lastModified: "2024-05-04T10:00:00Z", studentId: 7, classId: 1, unitDataId: 4, required: true, answers: eval4_82, comment: "Fantastic!" },
  { id: 83, lastModified: "2024-05-05T10:00:00Z", studentId: 7, classId: 1, unitDataId: 5, required: true, answers: eval5_82, comment: "Great work!" },
  { id: 84, lastModified: "2024-05-06T10:00:00Z", studentId: 7, classId: 1, unitDataId: 6, required: true, answers: eval6_82, comment: "Perfect!" },
  { id: 85, lastModified: "2024-05-07T10:00:00Z", studentId: 7, classId: 1, unitDataId: 7, required: true, answers: eval7_82, comment: "Excellent progress!" },
  { id: 86, lastModified: "2024-05-08T10:00:00Z", studentId: 7, classId: 1, unitDataId: 8, required: true, answers: eval8_82, comment: "Exemplary!" },
  { id: 87, lastModified: "2024-05-09T10:00:00Z", studentId: 7, classId: 1, unitDataId: 9, required: true, answers: eval9_82, comment: "Outstanding work!" },
  { id: 88, lastModified: "2024-05-10T10:00:00Z", studentId: 7, classId: 1, unitDataId: 10, required: true, answers: eval10_82, comment: "Superb!" },
  { id: 89, lastModified: "2024-05-11T10:00:00Z", studentId: 7, classId: 1, unitDataId: 11, required: true, answers: eval11_82, comment: "Excellent!" },
  { id: 90, lastModified: "2024-05-12T10:00:00Z", studentId: 7, classId: 1, unitDataId: 12, required: true, answers: eval12_82, comment: "Magnificent!" },
  { id: 91, lastModified: "2024-05-13T10:00:00Z", studentId: 7, classId: 1, unitDataId: 13, required: true, answers: eval13_82, comment: "Wonderful work!" },
  { id: 143, lastModified: "2024-05-14T10:00:00Z", studentId: 7, classId: 1, unitDataId: 14, required: true, answers: eval14_82, comment: "Wonderful!" },
  { id: 144, lastModified: "2024-05-15T10:00:00Z", studentId: 7, classId: 1, unitDataId: 15, required: true, answers: eval15_82, comment: "Excellent work!" },

  // Student 8 (Hugo Morin) - Needs improvement (58%)
  { id: 92, lastModified: "2024-05-01T10:00:00Z", studentId: 8, classId: 1, unitDataId: 1, required: true, answers: eval1_58, comment: "Some improvement" },
  { id: 93, lastModified: "2024-05-02T10:00:00Z", studentId: 8, classId: 1, unitDataId: 2, required: true, answers: eval2_58, comment: "Keep trying" },
  { id: 94, lastModified: "2024-05-03T10:00:00Z", studentId: 8, classId: 1, unitDataId: 3, required: true, answers: answers58, comment: "More practice" },
  { id: 95, lastModified: "2024-05-04T10:00:00Z", studentId: 8, classId: 1, unitDataId: 4, required: true, answers: eval4_58, comment: "Getting there" },
  { id: 96, lastModified: "2024-05-05T10:00:00Z", studentId: 8, classId: 1, unitDataId: 5, required: true, answers: eval5_58, comment: "Work harder" },
  { id: 97, lastModified: "2024-05-06T10:00:00Z", studentId: 8, classId: 1, unitDataId: 6, required: true, answers: eval6_58, comment: "Stay focused" },
  { id: 98, lastModified: "2024-05-07T10:00:00Z", studentId: 8, classId: 1, unitDataId: 7, required: true, answers: eval7_58, comment: "Needs support" },
  { id: 99, lastModified: "2024-05-08T10:00:00Z", studentId: 8, classId: 1, unitDataId: 8, required: true, answers: eval8_58, comment: "Let's practice" },
  { id: 100, lastModified: "2024-05-09T10:00:00Z", studentId: 8, classId: 1, unitDataId: 9, required: true, answers: eval9_58, comment: "Keep going" },
  { id: 101, lastModified: "2024-05-10T10:00:00Z", studentId: 8, classId: 1, unitDataId: 10, required: true, answers: eval10_58, comment: "More effort" },
  { id: 102, lastModified: "2024-05-11T10:00:00Z", studentId: 8, classId: 1, unitDataId: 11, required: true, answers: eval11_58, comment: "Review basics" },
  { id: 103, lastModified: "2024-05-12T10:00:00Z", studentId: 8, classId: 1, unitDataId: 12, required: true, answers: eval12_58, comment: "Focus needed" },
  { id: 104, lastModified: "2024-05-13T10:00:00Z", studentId: 8, classId: 1, unitDataId: 13, required: true, answers: eval13_58, comment: "Keep practicing" },
  { id: 145, lastModified: "2024-05-14T10:00:00Z", studentId: 8, classId: 1, unitDataId: 14, required: true, answers: eval14_58, comment: "Keep practicing" },
  { id: 146, lastModified: "2024-05-15T10:00:00Z", studentId: 8, classId: 1, unitDataId: 15, required: true, answers: eval15_58, comment: "Continue working" },

  // Student 9 (Isabelle Fortin) - Adequate (71%)
  { id: 105, lastModified: "2024-05-01T10:00:00Z", studentId: 9, classId: 1, unitDataId: 1, required: true, answers: eval1_71, comment: "Nice work" },
  { id: 106, lastModified: "2024-05-02T10:00:00Z", studentId: 9, classId: 1, unitDataId: 2, required: true, answers: eval2_71, comment: "Good progress" },
  { id: 107, lastModified: "2024-05-03T10:00:00Z", studentId: 9, classId: 1, unitDataId: 3, required: true, answers: answers71, comment: "Well done" },
  { id: 108, lastModified: "2024-05-04T10:00:00Z", studentId: 9, classId: 1, unitDataId: 4, required: true, answers: eval4_71, comment: "Good effort" },
  { id: 109, lastModified: "2024-05-05T10:00:00Z", studentId: 9, classId: 1, unitDataId: 5, required: true, answers: eval5_71, comment: "Solid work" },
  { id: 110, lastModified: "2024-05-06T10:00:00Z", studentId: 9, classId: 1, unitDataId: 6, required: true, answers: eval6_71, comment: "Nice effort" },
  { id: 111, lastModified: "2024-05-07T10:00:00Z", studentId: 9, classId: 1, unitDataId: 7, required: true, answers: eval7_71, comment: "Great work" },
  { id: 112, lastModified: "2024-05-08T10:00:00Z", studentId: 9, classId: 1, unitDataId: 8, required: true, answers: eval8_71, comment: "Improving" },
  { id: 113, lastModified: "2024-05-09T10:00:00Z", studentId: 9, classId: 1, unitDataId: 9, required: true, answers: eval9_71, comment: "Good job" },
  { id: 114, lastModified: "2024-05-10T10:00:00Z", studentId: 9, classId: 1, unitDataId: 10, required: true, answers: eval10_71, comment: "Well done" },
  { id: 115, lastModified: "2024-05-11T10:00:00Z", studentId: 9, classId: 1, unitDataId: 11, required: true, answers: eval11_71, comment: "Keep it up" },
  { id: 116, lastModified: "2024-05-12T10:00:00Z", studentId: 9, classId: 1, unitDataId: 12, required: true, answers: eval12_71, comment: "Excellent effort" },
  { id: 117, lastModified: "2024-05-13T10:00:00Z", studentId: 9, classId: 1, unitDataId: 13, required: true, answers: eval13_71, comment: "Good work" },
  { id: 147, lastModified: "2024-05-14T10:00:00Z", studentId: 9, classId: 1, unitDataId: 14, required: true, answers: eval14_71, comment: "Good work" },
  { id: 148, lastModified: "2024-05-15T10:00:00Z", studentId: 9, classId: 1, unitDataId: 15, required: true, answers: eval15_71, comment: "Solid effort" },

  // Student 10 (Julien Cloutier) - Excellent (81%)
  { id: 118, lastModified: "2024-05-01T10:00:00Z", studentId: 10, classId: 1, unitDataId: 1, required: true, answers: eval1_81, comment: "Excellent!" },
  { id: 119, lastModified: "2024-05-02T10:00:00Z", studentId: 10, classId: 1, unitDataId: 2, required: true, answers: eval2_81, comment: "Outstanding!" },
  { id: 120, lastModified: "2024-05-03T10:00:00Z", studentId: 10, classId: 1, unitDataId: 3, required: true, answers: answers81, comment: "Wonderful!" },
  { id: 121, lastModified: "2024-05-04T10:00:00Z", studentId: 10, classId: 1, unitDataId: 4, required: true, answers: eval4_81, comment: "Great work!" },
  { id: 122, lastModified: "2024-05-05T10:00:00Z", studentId: 10, classId: 1, unitDataId: 5, required: true, answers: eval5_81, comment: "Fantastic!" },
  { id: 123, lastModified: "2024-05-06T10:00:00Z", studentId: 10, classId: 1, unitDataId: 6, required: true, answers: eval6_81, comment: "Superb!" },
  { id: 124, lastModified: "2024-05-07T10:00:00Z", studentId: 10, classId: 1, unitDataId: 7, required: true, answers: eval7_81, comment: "Excellent progress!" },
  { id: 125, lastModified: "2024-05-08T10:00:00Z", studentId: 10, classId: 1, unitDataId: 8, required: true, answers: eval8_81, comment: "Exemplary!" },
  { id: 126, lastModified: "2024-05-09T10:00:00Z", studentId: 10, classId: 1, unitDataId: 9, required: true, answers: eval9_81, comment: "Outstanding work!" },
  { id: 127, lastModified: "2024-05-10T10:00:00Z", studentId: 10, classId: 1, unitDataId: 10, required: true, answers: eval10_81, comment: "Perfect!" },
  { id: 128, lastModified: "2024-05-11T10:00:00Z", studentId: 10, classId: 1, unitDataId: 11, required: true, answers: eval11_81, comment: "Excellent!" },
  { id: 129, lastModified: "2024-05-12T10:00:00Z", studentId: 10, classId: 1, unitDataId: 12, required: true, answers: eval12_81, comment: "Magnificent!" },
  { id: 130, lastModified: "2024-05-13T10:00:00Z", studentId: 10, classId: 1, unitDataId: 13, required: true, answers: eval13_81, comment: "Wonderful work!" },
  { id: 149, lastModified: "2024-05-14T10:00:00Z", studentId: 10, classId: 1, unitDataId: 14, required: true, answers: eval14_81, comment: "Excellent!" },
  { id: 150, lastModified: "2024-05-15T10:00:00Z", studentId: 10, classId: 1, unitDataId: 15, required: true, answers: eval15_81, comment: "Outstanding!" },

  // Student 7 (Gabrielle Gauthier) - Class 2
  { id: 151, lastModified: "2026-05-22T04:01:14.389Z", studentId: 7, classId: 2, unitDataId: 1, required: true, status: "success", answers: { bigLetters: { A: { name: true, sound: true }, B: { name: true, sound: true }, C: { name: true, sound: true }, D: { name: true, sound: true }, E: { name: true, sound: true }, F: { name: true, sound: true }, G: { name: true, sound: true }, H: { name: true, sound: true }, I: { name: true, sound: true }, J: { name: true, sound: true }, K: { name: true, sound: true }, L: { name: true, sound: true }, M: { name: true, sound: true }, N: { name: true, sound: true }, O: { name: true, sound: true }, P: { name: true, sound: true }, Q: { name: true, sound: true }, R: { name: true, sound: true }, S: { name: true, sound: true }, T: { name: true, sound: true }, U: { name: true, sound: true }, V: { name: true, sound: true }, W: { name: true, sound: true }, X: { name: true, sound: true }, Y: { name: true, sound: true }, Z: { name: true, sound: true } } }, comment: "" },

  // Student 11 (Léa Bergeron)
  { id: 152, lastModified: "2026-05-22T04:01:20.318Z", studentId: 11, classId: 2, unitDataId: 1, required: true, status: "needs-improvement", answers: { bigLetters: { A: { name: false, sound: false }, B: { name: false, sound: false }, C: { name: false, sound: false }, D: { name: false, sound: false }, E: { name: false, sound: false }, F: { name: false, sound: false }, G: { name: false, sound: false }, H: { name: false, sound: false }, I: { name: false, sound: false }, J: { name: false, sound: false }, K: { name: false, sound: false }, L: { name: false, sound: false }, M: { name: false, sound: false }, N: { name: false, sound: false }, O: { name: false, sound: false }, P: { name: false, sound: false }, Q: { name: false, sound: false }, R: { name: false, sound: false }, S: { name: false, sound: false }, T: { name: false, sound: false }, U: { name: false, sound: false }, V: { name: false, sound: false }, W: { name: false, sound: false }, X: { name: false, sound: false }, Y: { name: false, sound: false }, Z: { name: false, sound: false } } }, comment: "" },
  { id: 153, lastModified: "2026-05-22T04:01:23.654Z", studentId: 11, classId: 2, unitDataId: 2, required: true, status: "success", answers: { smallLetters: { a: { name: true, sound: true }, b: { name: true, sound: true }, c: { name: true, sound: true }, d: { name: true, sound: true }, e: { name: true, sound: true }, f: { name: true, sound: true }, g: { name: true, sound: true }, h: { name: true, sound: true }, i: { name: true, sound: true }, j: { name: true, sound: true }, k: { name: true, sound: true }, l: { name: true, sound: true }, m: { name: true, sound: true }, n: { name: true, sound: true }, o: { name: true, sound: true }, p: { name: true, sound: true }, q: { name: true, sound: true }, r: { name: true, sound: true }, s: { name: true, sound: true }, t: { name: true, sound: true }, u: { name: true, sound: true }, v: { name: true, sound: true }, w: { name: true, sound: true }, x: { name: true, sound: true }, y: { name: true, sound: true }, z: { name: true, sound: true } } }, comment: "" },
  { id: 155, lastModified: "2026-05-22T04:10:48.969Z", studentId: 11, classId: 2, unitDataId: 3, required: true, status: "success", answers: { bigLetters: { A: { correct: true }, B: { correct: true }, C: { correct: true }, D: { correct: true }, E: { correct: true }, F: { correct: true }, G: { correct: true }, H: { correct: true }, I: { correct: true }, J: { correct: true }, K: { correct: true }, L: { correct: true }, M: { correct: true }, N: { correct: true }, O: { correct: true }, P: { correct: true }, Q: { correct: true }, R: { correct: true }, S: { correct: true }, T: { correct: true }, U: { correct: true }, V: { correct: true }, W: { correct: true }, X: { correct: true }, Y: { correct: true }, Z: { correct: true } } }, comment: "" },
  { id: 156, lastModified: "2026-05-22T04:11:10.621Z", studentId: 11, classId: 2, unitDataId: 4, required: true, status: "needs-improvement", answers: { smallLetters: { a: { correct: false }, b: { correct: false }, c: { correct: false }, d: { correct: false }, e: { correct: false }, f: { correct: false }, g: { correct: false }, h: { correct: false }, i: { correct: false }, j: { correct: false }, k: { correct: false }, l: { correct: false }, m: { correct: false }, n: { correct: false }, o: { correct: false }, p: { correct: false }, q: { correct: false }, r: { correct: false }, s: { correct: false }, t: { correct: false }, u: { correct: false }, v: { correct: false }, w: { correct: false }, x: { correct: false }, y: { correct: false }, z: { correct: false } } }, comment: "" },
  { id: 157, lastModified: "2026-05-22T04:11:14.029Z", studentId: 11, classId: 2, unitDataId: 5, required: true, status: "success", answers: { rhyming: { "0": true, "1": true, "2": true, "3": true, "4": true }, segmenting: { "0": true, "1": true, "2": true, "3": true, "4": true }, syllableCounting: { "0": true, "1": true, "2": true, "3": true, "4": true } }, comment: "" },
  { id: 158, lastModified: "2026-05-22T04:11:32.298Z", studentId: 11, classId: 2, unitDataId: 6, required: true, status: "success", answers: { startOfWord: { "maison": true, "ballon": true, "soleil": true, "fenêtre": true, "chat": true }, endOfWord: { "chat": true, "pomme": true, "souris": true, "sac": true, "fil": true } }, comment: "" },

  // Student 13 (Sophie Martin)
  { id: 154, lastModified: "2026-05-22T04:01:29.800Z", studentId: 13, classId: 2, unitDataId: 1, required: true, status: "needs-improvement", answers: { bigLetters: { A: { name: false, sound: false }, B: { name: false, sound: false }, C: { name: false, sound: false }, D: { name: false, sound: false }, E: { name: false, sound: false }, F: { name: false, sound: false }, G: { name: false, sound: false }, H: { name: false, sound: false }, I: { name: false, sound: false }, J: { name: false, sound: false }, K: { name: false, sound: false }, L: { name: false, sound: false }, M: { name: false, sound: false }, N: { name: false, sound: false }, O: { name: false, sound: false }, P: { name: false, sound: false }, Q: { name: false, sound: false }, R: { name: false, sound: false }, S: { name: false, sound: false }, T: { name: false, sound: false }, U: { name: false, sound: false }, V: { name: false, sound: false }, W: { name: false, sound: false }, X: { name: false, sound: false }, Y: { name: false, sound: false }, Z: { name: false, sound: false } } }, comment: "" },
];