import { UnitData } from "./types";

export const unitData: UnitData[] = [
  {
    id: 1,
    unit: 1,
    evaluation: 1,
    title: "units.unit1-1",
    questions: {
      bigLetters: {
        "A": { name: true, sound: true },
        "B": { name: true, sound: true },
        "C": { name: true, sound: true },
        "D": { name: true, sound: true },
        "E": { name: true, sound: true },
        "F": { name: true, sound: true },
        "G": { name: true, sound: true },
        "H": { name: true, sound: true },
        "I": { name: true, sound: true },
        "J": { name: true, sound: true },
        "K": { name: true, sound: true },
        "L": { name: true, sound: true },
        "M": { name: true, sound: true },
        "N": { name: true, sound: true },
        "O": { name: true, sound: true },
        "P": { name: true, sound: true },
        "Q": { name: true, sound: true },
        "R": { name: true, sound: true },
        "S": { name: true, sound: true },
        "T": { name: true, sound: true },
        "U": { name: true, sound: true },
        "V": { name: true, sound: true },
        "W": { name: true, sound: true },
        "X": { name: true, sound: true },
        "Y": { name: true, sound: true },
        "Z": { name: true, sound: true },
      },
    },
  },
  {
    id: 2,
    unit: 1,
    evaluation: 2,
    title: "units.unit1-2",
    questions: {
      smallLetters: {
        "a": { name: true, sound: true },
        "b": { name: true, sound: true },
        "c": { name: true, sound: true },
        "d": { name: true, sound: true },
        "e": { name: true, sound: true },
        "f": { name: true, sound: true },
        "g": { name: true, sound: true },
        "h": { name: true, sound: true },
        "i": { name: true, sound: true },
        "j": { name: true, sound: true },
        "k": { name: true, sound: true },
        "l": { name: true, sound: true },
        "m": { name: true, sound: true },
        "n": { name: true, sound: true },
        "o": { name: true, sound: true },
        "p": { name: true, sound: true },
        "q": { name: true, sound: true },
        "r": { name: true, sound: true },
        "s": { name: true, sound: true },
        "t": { name: true, sound: true },
        "u": { name: true, sound: true },
        "v": { name: true, sound: true },
        "w": { name: true, sound: true },
        "x": { name: true, sound: true },
        "y": { name: true, sound: true },
        "z": { name: true, sound: true },
      },
    },
  },
  {
    id: 3,
    unit: 1,
    evaluation: 3,
    title: "units.unit1-3",
    questions: {
      bigLetters: {
        "A": { correct: true },
        "B": { correct: true },
        "C": { correct: true },
        "D": { correct: true },
        "E": { correct: true },
        "F": { correct: true },
        "G": { correct: true },
        "H": { correct: true },
        "I": { correct: true },
        "J": { correct: true },
        "K": { correct: true },
        "L": { correct: true },
        "M": { correct: true },
        "N": { correct: true },
        "O": { correct: true },
        "P": { correct: true },
        "Q": { correct: true },
        "R": { correct: true },
        "S": { correct: true },
        "T": { correct: true },
        "U": { correct: true },
        "V": { correct: true },
        "W": { correct: true },
        "X": { correct: true },
        "Y": { correct: true },
        "Z": { correct: true },
      },
    },
  },
  {
    id: 4,
    unit: 1,
    evaluation: 4,
    title: "units.unit1-4",
    questions: {
      smallLetters: {
        "a": { correct: true },
        "b": { correct: true },
        "c": { correct: true },
        "d": { correct: true },
        "e": { correct: true },
        "f": { correct: true },
        "g": { correct: true },
        "h": { correct: true },
        "i": { correct: true },
        "j": { correct: true },
        "k": { correct: true },
        "l": { correct: true },
        "m": { correct: true },
        "n": { correct: true },
        "o": { correct: true },
        "p": { correct: true },
        "q": { correct: true },
        "r": { correct: true },
        "s": { correct: true },
        "t": { correct: true },
        "u": { correct: true },
        "v": { correct: true },
        "w": { correct: true },
        "x": { correct: true },
        "y": { correct: true },
        "z": { correct: true },
      },
    },
  },
  {
    id: 5,
    unit: 1,
    evaluation: 5,
    title: "units.unit1-5",
    questions: {
      wordPairs: {
        "chat/rat": { correct: true },
        "fleur/table": { correct: true },
        "bateau/chapeau": { correct: true },
        "pain/main": { correct: true },
        "lune/porte": { correct: true },
      },
      syllables: {
        "ma-man": { correct: true },
        "ta-ble": { correct: true },
        "cha-peau": { correct: true },
        "voi-ture": { correct: true },
        "ba-na-ne": { correct: true },
      },
      numOfSyllables: {
        "chat": { correct: true },
        "livre": { correct: true },
        "éléphant": { correct: true },
        "chocolat": { correct: true },
        "papillon": { correct: true },
      },
    },
  },
  {
    id: 6,
    unit: 1,
    evaluation: 6,
    title: "units.unit1-6",
    questions: {
      startOfWord: {
        "maison": { sound: "/m/", correct: true },
        "ballon": { sound: "/b/", correct: true },
        "soleil": { sound: "/s/", correct: true },
        "fenêtre": { sound: "/f/", correct: true },
        "chat": { sound: "/ʃ/", correct: true },
      },
      endOfWord: {
        "chat": { sound: "/a/", correct: true },
        "pomme": { sound: "/m/", correct: true },
        "souris": { sound: "/i/", correct: true },
        "sac": { sound: "/k/", correct: true },
        "fil": { sound: "/l/", correct: true },
      },
    },
  },
  {
    id: 7,
    unit: 2,
    evaluation: 7,
    title: "units.unit2-1",
    questions: {
      syllables: {
        "ma": { correct: true },
        "li": { correct: true },
        "po": { correct: true },
        "ru": { correct: true },
        "sa": { correct: true },
        "il": { correct: true },
        "or": { correct: true },
        "pa": { correct: true },
        "mi": { correct: true },
        "bol": { correct: true },
      },
      soundRows: {
        0: { word: "a – e – t", sound: "/a/", correct: "a" },
        1: { word: "e – s – n", sound: "/e/", correct: "e" },
        2: { word: "t – a – s", sound: "/t/", correct: "t" },
        3: { word: "n – e – s", sound: "/s/", correct: "s" },
        4: { word: "a – t – n", sound: "/n/", correct: "n" },
      },
    },
  },
  {
    id: 8,
    unit: 3,
    evaluation: 8,
    title: "units.unit3-1",
    questions: {
      frequentWords: {
        "le": { correct: true },
        "de": { correct: true },
        "un": { correct: true },
        "petit": { correct: true },
        "papa": { correct: true },
        "maman": { correct: true },
        "c'est": { correct: true },
        "voici": { correct: true },
        "dit": { correct: true },
        "ami": { correct: true },
        "avec": { correct: true },
        "grand": { correct: true },
        "a": { correct: true },
        "regarde": { correct: true },
        "pour": { correct: true },
        "une": { correct: true },
        "elle": { correct: true },
        "est": { correct: true },
        "il y a": { correct: true },
        "ici": { correct: true },
        "dans": { correct: true },
        "mon": { correct: true },
        "aller": { correct: true },
        "cherche": { correct: true },
        "j'aime": { correct: true },
      },
      openClosedList: {
        "ba": { correct: true },
        "li": { correct: true },
        "por": { correct: true },
        "val": { correct: true },
        "tur": { correct: true },
      },
      complexList: {
        "pla": { correct: true },
        "bri": { correct: true },
        "tro": { correct: true },
        "flan": { correct: true },
        "gros": { correct: true },
      },
    },
  },
  {
    id: 9,
    unit: 4,
    evaluation: 9,
    title: "units.unit4-1",
    questions: {
      frequentWordsSlice: {
        "maman": { correct: true },
        "c'est": { correct: true },
        "voici": { correct: true },
        "dit": { correct: true },
        "ami": { correct: true },
        "avec": { correct: true },
        "grand": { correct: true },
        "a": { correct: true },
        "regarde": { correct: true },
        "pour": { correct: true },
        "une": { correct: true },
        "elle": { correct: true },
        "est": { correct: true },
        "il y a": { correct: true },
        "ici": { correct: true },
      },
    },
  },
  {
    id: 10,
    unit: 5,
    evaluation: 10,
    title: "units.unit5-1",
    questions: {
      data: {
        "chat": { correct: true },
        "agneau": { correct: true },
        "montagne": { correct: true },
        "oiseau": { correct: true },
        "maison": { correct: true },
        "bateau": { correct: true },
        "soupe": { correct: true },
        "lait": { correct: true },
        "auto": { correct: true },
        "poire": { correct: true },
      },
    },
  },
  {
    id: 11,
    unit: 6,
    evaluation: 11,
    title: "units.unit6-1",
    questions: {
      data: {
        "grand": { forms: ["grand", "grande", "grands", "grandes"], correct: true },
        "petit": { forms: ["petit", "petite", "petits", "petites"], correct: true },
        "beau": { forms: ["beau", "belle", "beaux", "belles"], correct: true },
        "chaud": { forms: ["chaud", "chaude", "chauds", "chaudes"], correct: true },
        "blanc": { forms: ["blanc", "blanche", "blancs", "blanches"], correct: true },
      },
    },
  },
  {
    id: 12,
    unit: 7,
    evaluation: 12,
    title: "units.unit7-1",
    questions: {
      data: {
        "Le chat dort sur le canapé.": { correct: true },
        "Ma maman dort sur le canapé.": { correct: true },
        "L'enfant dort sur le canapé.": { correct: true },
      },
    },
  },
  {
    id: 13,
    unit: 8,
    evaluation: 13,
    title: "units.unit8-1",
    questions: {
      data: {
        "travail": { correct: true },
        "soleil": { correct: true },
        "réveil": { correct: true },
        "fauteuil": { correct: true },
        "écureuil": { correct: true },
        "grenouille": { correct: true },
        "chandail": { correct: true },
        "appareil": { correct: true },
        "seuil": { correct: true },
        "citrouille": { correct: true },
      },
    },
  },
  {
    id: 14,
    unit: 9,
    evaluation: 14,
    title: "units.unit9-1",
    questions: {
      data: {
          "Où vont Sophie et Marc?": { answer: "Au parc", correct: true },
          "Qui va au parc avec eux?": { answer: "Leur chien Félix / Félix", correct: true },
          "De quelle couleur est le ballon?": { answer: "Rouge", correct: true },
          "Que font-ils après le jeu?": { answer: "Ils mangent des sandwichs et boivent du jus", correct: true },
          "Comment se sentent-ils à la fin?": { answer: "Fatigués mais heureux", correct: true },
      }
    },
  },
  {
    id: 15,
    unit: 10,
    evaluation: 15,
    title: "units.unit10-1",
    questions: {
      data: {
        "Comment s'appelle le chat?": { answer: "Minou", correct: true },
        "De quelle couleur est le chat?": { answer: "Noir et blanc", correct: true },
        "Qu'est-ce que Minou aime faire?": { answer: "Dormir sur le lit et jouer avec une balle rouge", correct: true },
        "De quelle couleur est son bol?": { answer: "Bleu", correct: true },
        "Quand est-ce que Minou boit du lait?": { answer: "Tous les matins", correct: true },
      },
    },
  },
];
